### ISSUE TITLE
Jedi breaks Ipython

### ISSUE THREAD

**Issue by yurzo** [davidhalter/jedi#1720] opened 2020-12-28 23:19 UTC
0.18.0 breaks ipython. See https://github.com/ipython/ipython/issues/12745#issuecomment-751891030

**Comment by codylane** [comment] 2020-12-28 23:26
I can also confirm that I'm affected by the same issue with Jedi when trying to use ipython as noted in the comment above.  Please let me know if there is anything I can do to help.

**Comment by PeterJCLaw** [comment] 2020-12-28 23:43
This looks like a duplicate of #1714.
The IPython issue looks like a duplicate of https://github.com/ipython/ipython/issues/12740.

**Closed by PeterJCLaw** 2020-12-28 23:43 UTC
