### ISSUE TITLE
IPython crashes on tab completion

### ISSUE THREAD

**Issue by thorstenkampe** [davidhalter/jedi#1716] opened 2020-12-26 16:16 UTC
Since the upgrade to the latest version yesterday, IPython - which uses jedi - crashes on any attempt of tab completion. See https://github.com/ipython/ipython/issues/12742 . Reverting to version 17.2 resolves the issue.

**Comment by davidhalter** [comment] 2020-12-26 16:29
Duplicate of https://github.com/davidhalter/jedi/issues/1714.

**Closed by davidhalter** 2020-12-26 16:29 UTC
