### ISSUE TITLE
AttributeError: 'generator' object has no attribute '__objclass__'

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#513] opened 2014-11-28 12:04 UTC
When the input is:
```python
a = (randrange(10) for _ in xrange(100))
next(a)
```

It crashes with the following traceback
```python
Traceback (most recent call last):
 ...
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/prompt_toolkit/contrib/python_input.py", line 481, in get_completions
    completions = script.completions()
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 648, in _simple_complete
    return super(Interpreter, self)._simple_complete(path, like)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 246, in eval_call_path
    return self.follow_path(path, types, scope)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 260, in follow_path
    fp = self._follow_path(iter_paths[i], typ, call_scope)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 296, in _follow_path
    result = self.execute(typ, current)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 336, in execute
    stmts = er.FunctionExecution(self, obj, params).get_return_types(evaluate_generator)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 108, in run
    result = func(execution, evaluate_generator)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 437, in get_return_types
    stmts += self._evaluator.eval_statement(r)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 47, in find
    types = self._names_to_types(names, resolve_decorator)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 216, in _names_to_types
    types += self._eval_param(typ)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 322, in _eval_param
    return res_new + evaluator.eval_statement(param, seek_name=unicode(self.name_str))
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 195, in eval_statement_element
    for s in element))
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 195, in <genexpr>
    for s in element))
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 46, in find
    names = self.filter_name(scopes)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 89, in filter_name
    scope = name.parent.parent
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/api/interpreter.py", line 97, in parent
    return compiled.create(self._evaluator, self._value, module, module)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 409, in wrapper
    result = func(evaluator, obj, parent, module)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 424, in create
    faked = fake.get_faked(module and module.obj, obj)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/compiled/fake.py", line 102, in get_faked
    result = _faked(module, obj, name)
  File "/home/jonathan/env/test4/local/lib/python2.7/site-packages/jedi/evaluate/compiled/fake.py", line 86, in _faked
    cls = search_scope(faked_mod, obj.__objclass__.__name__)
AttributeError: 'generator' object has no attribute '__objclass__'
```

**Comment by davidhalter** [comment] 2015-03-24 16:38
Fixed by rewriting it (see comment in #514). If it's still an issue, let me know, I tried to reproduce it, but couldn't, so I assume it's fixed, because of the changes.

**Closed by davidhalter** 2015-03-24 16:38 UTC
Labels: bug
