### ISSUE TITLE
KeyError: <String: "…">

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#681] opened 2016-01-11 09:35 UTC
Jedi 0.9.0, Python 2.7.11:

```
Traceback (most recent call last):
  File "/home/gav/.emacs.d/lisp/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/server.py", line 95, in rpc_get_completions
    get_source(source), offset)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 247, in _eval_atom
    return [iterable.Array(self, atom)]
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/iterable.py", line 198, in __init__
    self.type = Array.mapping[atom.children[0]]
KeyError: <String: "cryptography is a package which provides cryptographic recipes">
```

No reproduction, so not sure if this helps at all, but I'd figure I'd report it.

Originally from jorgenschaefer/elpy#762

**Comment by ugopozo** [comment] 2016-01-15 18:44
I can reproduce this bug with the following steps:

* Create a directory, say multi/, containing two files, \_\_init\_\_.py and multiline.py.

* On multiline.py, define a multiline string, i.e.:

```python
MY_BIG_STRING = (
    "my "
    "big "
    "string."
)
```
* On \_\_init\_\_.py, import the string and then re-export with \_\_all\_\_:

```python
from .multiline import MY_BIG_STRING

__all__ = ["MY_BIG_STRING"]
```

* Finally, creating a new file in the parent directory (the one that contains the multi/ directory) and trying to get completions on multi will trigger the error:

```python
import multi

multi.
```

**Comment by davidhalter** [comment] 2016-07-12 08:14
@ugopozo Could you please retry this?

**Comment by ugopozo** [comment] 2016-07-12 13:35
@davidhalter It works for me now, thanks!

**Comment by davidhalter** [comment] 2016-07-13 07:16
I have really played around with multi-strings and they seem  to work.

I really cannot reproduce this. I think I was able to a few months ago, but not anymore. I'm closing, but please let me know if there are still issues!

**Closed by davidhalter** 2016-07-13 07:16 UTC
Labels: bug
