### ISSUE TITLE
autoimport e.g. from os import *

### ISSUE THREAD

**Issue by SebastianBolte** [davidhalter/jedi#1866] opened 2022-07-07 15:17 UTC
I know that this feature will not be implemented in the near future(https://github.com/davidhalter/jedi-vim/issues/736#issuecomment-751416521) but maybe you can tell me here also where I have to adapt the jedi - code. May be you know a really fast solution which is more like a hack but what I can use local for my requirements?

**Comment by davidhalter** [comment] 2022-07-07 20:05
The thing is that there is not really a fast solution, otherwise I would already have done it :). The problem is really that the whole architecture was never really done for problems like this one. There is no name binding procedure and there's also no form of caching (because there's no good invalidation for type inference). You could potentially just iterate over all names in a file and use goto on the right ones and then search for definitions in other files. But that's reallly hacky. The Rust code that I'm currently writing has a different architecture and with that it should be easily possible to implement auto imports.

I think #1059 is pretty much the reason why this is not possible. Closing this one, because there's nothing to do here for now.

Feel free to continue discussing this though.

**Closed by davidhalter** 2022-07-07 20:05 UTC
