### ISSUE TITLE
PyGObject completion fails in vim and deoplete

### ISSUE THREAD

**Issue by Jeansen** [davidhalter/jedi#1345] opened 2019-06-14 20:21 UTC
I've started with Python recently and tried some minimal code in Vim (which so far I used for Bash, Perl and the like).

I've created a venv and installed PyQt5. With that I get perfect completions.

But with PyGObject I get some exception. Here is the sample code:

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```

The venv I prepared following this: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started

The completion for `Gtk.` works fine, but when I type `win.`, I get:

```
[deoplete] Traceback (most recent call last):^@ File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 43, in filter_names^@ k = (new.name, new.complete) # key^@ File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/a
pi/classes.py", line 434, in complete^@ return self._complete(True)^@ File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/classes.py", line 403, in _complete^@ if self._name.api_type == 'param' and self._stack is not None:^@ File "/home/marcel/.vim/plugged/deoplete-jed
i/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/compiled/context.py", line 237, in api_type^@ return next(iter(self.infer())).api_type^@StopIteration^@^@the above exception was the direct cause of the following exception:^@^@Traceback (most recent call last):^@ File "/home/marcel/.vim//plugged/deoplete.nvim
/rplugin/python3/deoplete/child.py", line 182, in _gather_results^@ result = self._get_result(context, source)^@ File "/home/marcel/.vim//plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 241, in _get_result^@ ctx['candidates'] = source.gather_candidates(ctx)^@ File "/home/marcel/.vim/plugged/deop
lete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper^@ return func(self, *args, **kwargs)^@ File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 170, in gather_candidates^@ completions = self.get_completions(script)^@ File
"/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper^@ return func(self, *args, **kwargs)^@ File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 123, in get_completions^@ return script.comple
tions()^@ File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/init.py", line 179, in completions^@ completions = completion.completions()^@ File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 103, in compl
etions^@ return sorted(completions, key=lambda x: (x.name.startswith('__'),^@RuntimeError: generator raised StopIteration^@error from jedi: generator raised StopIteration. Use :messages / see above for error details
```

**Comment by davidhalter** [comment] 2019-06-21 21:47
Since I just released Jedi 0.14.0, could you retry with it? I will not be fixing anything in the old versions anymore.

Also please post a traceback with proper newlines next time ;-)

**Comment by Jeansen** [comment] 2019-06-23 15:48
@davidhalter 
I've updated to jedi 14.0 and tried the example above again. But nothing changes so far. I'd like to give you a well formatted trace, but this is how vim spits it at me, sorry.

```
[deoplete] Traceback (most recent call last):^@  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 44, in filter_names^@    k = (new.name, new.complete)  # key^@  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/a
pi/classes.py", line 439, in complete^@    return self._complete(True)^@  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/classes.py", line 408, in _complete^@    if self._name.api_type == 'param' and self._stack is not None:^@  File "/home/marcel/.vim/plugged/deoplete-jed
i/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/compiled/context.py", line 284, in api_type^@    return next(iter(self.infer())).api_type^@StopIteration^@^@The above exception was the direct cause of the following exception:^@^@Traceback (most recent call last):^@  File "/home/marcel/.vim//plugged/deoplete.nvim
/rplugin/python3/deoplete/child.py", line 182, in _gather_results^@    result = self._get_result(context, source)^@  File "/home/marcel/.vim//plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 241, in _get_result^@    ctx['candidates'] = source.gather_candidates(ctx)^@  File "/home/marcel/.vim/plugged/deop
lete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper^@    return func(self, *args, **kwargs)^@  File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 170, in gather_candidates^@    completions = self.get_completions(script)^@  File
 "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper^@    return func(self, *args, **kwargs)^@  File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 123, in get_completions^@    return script.comple
tions()^@  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 216, in completions^@    return completion.completions()^@  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 104, in completions^
@    return sorted(completions, key=lambda x: (x.name.startswith('__'),^@RuntimeError: generator raised StopIteration^@Error from jedi: generator raised StopIteration.  Use :messages / see above for error details.
.
```

**Comment by Jeansen** [comment] 2019-06-23 15:49
Please let me know, how I might better debug this to be of more help. So far, Python is still new to me (just started a couple days back).

**Comment by davidhalter** [comment] 2019-06-23 16:38
The point is that if you do it that I don't have to do it, because I have to answer 1-2 issues a day:

```
>>> print('\n'.join(x.split('^@')))
Traceback (most recent call last):
  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 44, in filter_names
    k = (new.name, new.complete)  # key
  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/a
pi/classes.py", line 439, in complete
    return self._complete(True)
  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/classes.py", line 408, in _complete
    if self._name.api_type == 'param' and self._stack is not None:
  File "/home/marcel/.vim/plugged/deoplete-jed
i/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/compiled/context.py", line 284, in api_type
    return next(iter(self.infer())).api_type
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marcel/.vim//plugged/deoplete.nvim
/rplugin/python3/deoplete/child.py", line 182, in _gather_results
    result = self._get_result(context, source)
  File "/home/marcel/.vim//plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 241, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/marcel/.vim/plugged/deop
lete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 170, in gather_candidates
    completions = self.get_completions(script)
  File
 "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/marcel/.vim//plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 123, in get_completions
    return script.comple
tions()
  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 216, in completions
    return completion.completions()
  File "/home/marcel/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 104, in completions^
@    return sorted(completions, key=lambda x: (x.name.startswith('__'),
RuntimeError: generator raised StopIteration
Error from jedi: generator raised StopIteration.  Use :messages / see above for error details.
```

**Comment by davidhalter** [comment] 2019-06-23 16:39
Probably a duplicate of #1351

**Comment by Jeansen** [comment] 2019-06-23 21:23
@davidhalter Thanks for the quick reply. Then let's wait for the PR mentioned in #1351 and then I'll try again.

**Comment by davidhalter** [comment] 2019-06-24 21:59
This looks exactly like what #1352 was fixing. Let me know if it there is still an issue, but I consider this fixed.

**Closed by davidhalter** 2019-06-24 21:59 UTC
Labels: discussion

**Comment by Jeansen** [comment] 2019-06-25 15:49
I've installed the master branch version with `pip install --user -e git://github.com/davidhalter/jedi.git#egg=jedi`

From what I see with `pip list | grep jedi', I use the correct version. Master is current. But the error stays the same.

**Comment by davidhalter** [comment] 2019-06-28 07:11
Can you run it with direct jedi calls? I don't want to debug your vim here, because that might depend on a couple of things. Please use something like this:

```
code = '''
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()
win.
'''
Script(code).completions()
```

If that doesn't fail, everything is probably fine. And if it does, post a traceback please.

**Comment by Jeansen** [comment] 2019-06-28 18:40
```
python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> code='''
... import gi
... gi.require_version("Gtk", "3.0")
... from gi.repository import Gtk
... 
... window = Gtk.Window(title="Hello World")
... window.
... '''
>>> jedi.Script(code).completions()
[<Completion: abs>, <Completion: all>, <Completion: any>, <Completion: ArithmeticError>, <Completion: ascii>, <Completion: assert>, <Completion: AssertionError>, <Completion: async>, <Completion: AttributeError>, <Completion: await>, <Completion: BaseException>, <Completion: bin>, <Completion: BlockingIOError>, <Completion: bool>, <Completion: break>, <Completion: breakpoint>, <Completion: BrokenPipeError>, <Completion: BufferError>, <Completion: bytearray>, <Completion: bytes>, <Completion: BytesWarning>, <Completion: callable>, <Completion: ChildProcessError>, <Completion: chr>, <Completion: class>, <Completion: classmethod>, <Completion: compile>, <Completion: complex>, <Completion: ConnectionAbortedError>, <Completion: ConnectionError>, <Completion: ConnectionRefusedError>, <Completion: ConnectionResetError>, <Completion: continue>, <Completion: copyright>, <Completion: credits>, <Completion: def>, <Completion: del>, <Completion: delattr>, <Completion: DeprecationWarning>, <Completion: dict>, <Completion: dir>, <Completion: divmod>, <Completion: ellipsis>, <Completion: Ellipsis>, <Completion: enumerate>, <Completion: EnvironmentError>, <Completion: EOFError>, <Completion: eval>, <Completion: Exception>, <Completion: exec>, <Completion: exit>, <Completion: False>, <Completion: FileExistsError>, <Completion: FileNotFoundError>, <Completion: filter>, <Completion: float>, <Completion: FloatingPointError>, <Completion: for>, <Completion: format>, <Completion: from>, <Completion: frozenset>, <Completion: FutureWarning>, <Completion: GeneratorExit>, <Completion: getattr>, <Completion: gi>, <Completion: global>, <Completion: globals>, <Completion: Gtk>, <Completion: hasattr>, <Completion: hash>, <Completion: help>, <Completion: hex>, <Completion: id>, <Completion: if>, <Completion: import>, <Completion: ImportError>, <Completion: ImportWarning>, <Completion: IndentationError>, <Completion: IndexError>, <Completion: input>, <Completion: int>, <Completion: InterruptedError>, <Completion: IOError>, <Completion: IsADirectoryError>, <Completion: isinstance>, <Completion: issubclass>, <Completion: iter>, <Completion: KeyboardInterrupt>, <Completion: KeyError>, <Completion: lambda>, <Completion: len>, <Completion: license>, <Completion: list>, <Completion: locals>, <Completion: LookupError>, <Completion: map>, <Completion: max>, <Completion: MemoryError>, <Completion: memoryview>, <Completion: min>, <Completion: ModuleNotFoundError>, <Completion: NameError>, <Completion: next>, <Completion: None>, <Completion: nonlocal>, <Completion: not>, <Completion: NotADirectoryError>, <Completion: NotImplemented>, <Completion: NotImplementedError>, <Completion: object>, <Completion: oct>, <Completion: open>, <Completion: ord>, <Completion: OSError>, <Completion: OverflowError>, <Completion: pass>, <Completion: PendingDeprecationWarning>, <Completion: PermissionError>, <Completion: pow>, <Completion: print>, <Completion: ProcessLookupError>, <Completion: property>, <Completion: quit>, <Completion: raise>, <Completion: range>, <Completion: RecursionError>, <Completion: ReferenceError>, <Completion: repr>, <Completion: ResourceWarning>, <Completion: return>, <Completion: reversed>, <Completion: round>, <Completion: RuntimeError>, <Completion: RuntimeWarning>, <Completion: set>, <Completion: setattr>, <Completion: slice>, <Completion: sorted>, <Completion: staticmethod>, <Completion: StopAsyncIteration>, <Completion: StopIteration>, <Completion: str>, <Completion: sum>, <Completion: super>, <Completion: SyntaxError>, <Completion: SyntaxWarning>, <Completion: SystemError>, <Completion: SystemExit>, <Completion: TabError>, <Completion: TimeoutError>, <Completion: True>, <Completion: try>, <Completion: tuple>, <Completion: type>, <Completion: TypeError>, <Completion: UnboundLocalError>, <Completion: UnicodeDecodeError>, <Completion: UnicodeEncodeError>, <Completion: UnicodeError>, <Completion: UnicodeTranslateError>, <Completion: UnicodeWarning>, <Completion: UserWarning>, <Completion: ValueError>, <Completion: vars>, <Completion: Warning>, <Completion: while>, <Completion: window>, <Completion: WindowsError>, <Completion: with>, <Completion: yield>, <Completion: ZeroDivisionError>, <Completion: zip>, <Completion: __doc__>, <Completion: __file__>, <Completion: __import__>, <Completion: __name__>, <Completion: __package__>]
>>> 
```

**Comment by Jeansen** [comment] 2019-06-28 18:41
Looks good. So,will get back to the author of deoplete.

**Comment by Jeansen** [comment] 2019-06-28 18:43
Here is what it looks like with version 0.13.2.

```
python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> code='''
... import gi
... gi.require_version("Gtk", "3.0")
... from gi.repository import Gtk
... 
... window = Gtk.Window(title="Hello World")
... window.
... '''
>>> jedi.Script(code).completions()
[<Completion: abs>, <Completion: all>, <Completion: any>, <Completion: ArithmeticError>, <Completion: ascii>, <Completion: assert>, <Completion: AssertionError>, <Completion: async>, <Completion: AttributeError>, <Completion: await>, <Completion: BaseException>, <Completion: bin>, <Completion: BlockingIOError>, <Completion: bool>, <Completion: break>, <Completion: breakpoint>, <Completion: BrokenPipeError>, <Completion: BufferError>, <Completion: bytearray>, <Completion: bytes>, <Completion: BytesWarning>, <Completion: callable>, <Completion: ChildProcessError>, <Completion: chr>, <Completion: class>, <Completion: classmethod>, <Completion: compile>, <Completion: complex>, <Completion: ConnectionAbortedError>, <Completion: ConnectionError>, <Completion: ConnectionRefusedError>, <Completion: ConnectionResetError>, <Completion: continue>, <Completion: copyright>, <Completion: credits>, <Completion: def>, <Completion: del>, <Completion: delattr>, <Completion: DeprecationWarning>, <Completion: dict>, <Completion: dir>, <Completion: divmod>, <Completion: Ellipsis>, <Completion: enumerate>, <Completion: EnvironmentError>, <Completion: EOFError>, <Completion: eval>, <Completion: Exception>, <Completion: exec>, <Completion: exit>, <Completion: False>, <Completion: FileExistsError>, <Completion: FileNotFoundError>, <Completion: filter>, <Completion: float>, <Completion: FloatingPointError>, <Completion: for>, <Completion: format>, <Completion: from>, <Completion: frozenset>, <Completion: FutureWarning>, <Completion: GeneratorExit>, <Completion: getattr>, <Completion: gi>, <Completion: global>, <Completion: globals>, <Completion: Gtk>, <Completion: hasattr>, <Completion: hash>, <Completion: help>, <Completion: hex>, <Completion: id>, <Completion: if>, <Completion: import>, <Completion: ImportError>, <Completion: ImportWarning>, <Completion: IndentationError>, <Completion: IndexError>, <Completion: input>, <Completion: int>, <Completion: InterruptedError>, <Completion: IOError>, <Completion: IsADirectoryError>, <Completion: isinstance>, <Completion: issubclass>, <Completion: iter>, <Completion: KeyboardInterrupt>, <Completion: KeyError>, <Completion: lambda>, <Completion: len>, <Completion: license>, <Completion: list>, <Completion: locals>, <Completion: LookupError>, <Completion: map>, <Completion: max>, <Completion: MemoryError>, <Completion: memoryview>, <Completion: min>, <Completion: ModuleNotFoundError>, <Completion: NameError>, <Completion: next>, <Completion: None>, <Completion: nonlocal>, <Completion: not>, <Completion: NotADirectoryError>, <Completion: NotImplemented>, <Completion: NotImplementedError>, <Completion: object>, <Completion: oct>, <Completion: open>, <Completion: ord>, <Completion: OSError>, <Completion: OverflowError>, <Completion: pass>, <Completion: PendingDeprecationWarning>, <Completion: PermissionError>, <Completion: pow>, <Completion: print>, <Completion: ProcessLookupError>, <Completion: property>, <Completion: quit>, <Completion: raise>, <Completion: range>, <Completion: RecursionError>, <Completion: ReferenceError>, <Completion: repr>, <Completion: ResourceWarning>, <Completion: return>, <Completion: reversed>, <Completion: round>, <Completion: RuntimeError>, <Completion: RuntimeWarning>, <Completion: set>, <Completion: setattr>, <Completion: slice>, <Completion: sorted>, <Completion: staticmethod>, <Completion: StopAsyncIteration>, <Completion: StopIteration>, <Completion: str>, <Completion: sum>, <Completion: super>, <Completion: SyntaxError>, <Completion: SyntaxWarning>, <Completion: SystemError>, <Completion: SystemExit>, <Completion: TabError>, <Completion: TimeoutError>, <Completion: True>, <Completion: try>, <Completion: tuple>, <Completion: type>, <Completion: TypeError>, <Completion: UnboundLocalError>, <Completion: UnicodeDecodeError>, <Completion: UnicodeEncodeError>, <Completion: UnicodeError>, <Completion: UnicodeTranslateError>, <Completion: UnicodeWarning>, <Completion: UserWarning>, <Completion: ValueError>, <Completion: vars>, <Completion: Warning>, <Completion: while>, <Completion: window>, <Completion: with>, <Completion: yield>, <Completion: ZeroDivisionError>, <Completion: zip>, <Completion: __build_class__>, <Completion: __debug__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __import__>, <Completion: __loader__>, <Completion: __name__>, <Completion: __package__>, <Completion: __spec__>]
>>> 
```

**Comment by davidhalter** [comment] 2019-06-29 06:12
I just realized that you probably have to do `[c.type for c in jedi.Script(code).completions()]`. Otherwise you will not be able to reproduce the error.

**Comment by Jeansen** [comment] 2019-06-29 13:44
Tried, as you suggested, but still seems fine with jedi 0.13.2
```
python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> code='''
... import gi
... gi.require_version("Gtk", "3.0")
... from gi.repository import Gtk
... window = Gtk.Window(title="Hello World")
... window.
... '''
>>> [c.type for c in jedi.Script(code).completions()]
['function', 'function', 'function', 'class', 'function', 'keyword', 'class', 'keyword', 'class', 'keyword', 'class', 'function', 'class', 'class', 'keyword', 'function', 'class', 'class', 'class', 'class', 'class', 'function', 'class', 'function', 'keyword', 'class', 'function', 'class', 'class', 'class', 'class', 'class', 'keyword', 'instance', 'instance', 'keyword', 'keyword', 'function', 'class', 'class', 'function', 'function', 'instance', 'class', 'class', 'class', 'function', 'class', 'function', 'instance', 'keyword', 'class', 'class', 'class', 'class', 'class', 'keyword', 'function', 'keyword', 'class', 'class', 'class', 'function', 'module', 'keyword', 'function', 'module', 'function', 'function', 'instance', 'function', 'function', 'keyword', 'keyword', 'class', 'class', 'class', 'class', 'function', 'class', 'class', 'class', 'class', 'function', 'function', 'function', 'class', 'class', 'keyword', 'function', 'instance', 'class', 'function', 'class', 'class', 'function', 'class', 'class', 'function', 'class', 'class', 'function', 'keyword', 'keyword', 'keyword', 'class', 'instance', 'class', 'class', 'function', 'function', 'function', 'class', 'class', 'keyword', 'class', 'class', 'function', 'function', 'class', 'class', 'instance', 'keyword', 'class', 'class', 'class', 'function', 'class', 'keyword', 'class', 'function', 'class', 'class', 'class', 'function', 'class', 'function', 'class', 'class', 'class', 'class', 'function', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'keyword', 'keyword', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'class', 'function', 'class', 'keyword', 'statement', 'keyword', 'keyword', 'class', 'class', 'function', 'instance', 'instance', 'instance', 'function', 'class', 'instance', 'instance', 'instance']
```

So, I think the problem must be with deoplete or somewhere between ...

**Comment by Shougo** [comment] 2019-06-30 09:28
The fix must be merged in deoplete-jedi.

**Comment by Jeansen** [comment] 2019-07-01 14:58
Works like expected now, even with jedi 0.13.2. Thx @Shougo.
