### ISSUE TITLE
All references are not listed, when use find all references

### ISSUE THREAD

**Issue by iyuhang** [davidhalter/jedi#1520] opened 2020-03-05 16:03 UTC
Environment data
VS Code version: 1.42.1
Python Extension version: 2020.2.64
Python Version: 3.7, 64-bit
OS and version: mac os

Actual behavior
In the project, if you right click on the function definition for "configure_params" in the contrived.py file, and click "Find All References", it will not find any references outside of the current file. However, if you click "Find All References" in the prove_its_broken.py, it will find two references - one from prove_its_broken.py and the other from contrived.py.

Expected behavior
I would expect ALL references to be found when you click find all references on the function header.

as report in this issue, today I have the same issue , Find all references can only show partly
#810

**Comment by davidhalter** [comment] 2020-03-05 20:56
I cannot follow your descriptions, really. One thing to do would be to upgrade Jedi to 0.16.0 (otherwise it just makes no sense, because there were significant changes). However Jedi 0.16.0 is not really supported by them. So you might just try pip upgrading it. I think that might work, but it's at your own risk, because they might use some deleted APIs.

If you really want to debug this and show me that this is an issue, you have to reproduce it with `jedi.Script(path=path, line=line, column=column).get_references()`. That would help a lot.

Since it will take quite a bit of time until the guys working on Jedi's language server will be finished, I'm closing this issue for now. Happy to discuss and reopen however if you provide direct code examples (working with Jedi's API is not hard).

PS: Your issue link doesn't make sense.

**Closed by davidhalter** 2020-03-05 20:56 UTC
