### ISSUE TITLE
Numbers in packages / modules

### ISSUE THREAD

**Issue by ganwell** [davidhalter/jedi#732] opened 2016-06-13 17:37 UTC
I have a module c2rst.py in the package c2rst:

```python
import c2rst.c2rst # (c2rst/c2rst.py)
```

in c2rst.py relative imports don't complete.

Please let me know if this rings any bells or how I can dig deeper?

**Comment by davidhalter** [comment] 2016-06-16 20:18
Could point me to the source code of that module or is it proprietary?

**Comment by ganwell** [comment] 2016-06-16 20:33
Of course:

https://github.com/ganwell/c4irp/blob/basic-connection-handling/c4irp/chirp.py

But I temporaly fixed it, you have to break it again :-)

```bash
cd c4irp/
mv chirp.py c4irp.py
```

**Comment by davidhalter** [comment] 2016-07-31 16:54
Where do you complete? It might have been fixed in the current dev branch (I cannot reproduce).

But in any case it might be hard to actually do right. There's no way for Jedi to exactly know in which package you mean, unless it's properly on the sys.path.

Jedi uses certain approaches to guess the sys.path if nothing is working, so...

Let me know if it works for you! I'm closing, because I think this was fixed.

**Closed by davidhalter** 2016-07-31 16:54 UTC
Labels: bug, feature, high_prio

**Comment by ganwell** [comment] 2016-08-02 10:46
@davidhalter I decided having numbers in python modules is bad idea an removed them. I think the issue is fixed. Anyone can reopen it.
