### ISSUE TITLE
many extra processes

### ISSUE THREAD

**Issue by angrycandy** [davidhalter/jedi#1256] opened 2018-11-26 19:01 UTC
* With my old .python-environments at most two processes are created for each emacs:
```
/home/bfw/.emacs.d/.python-environments/i386/bin/python2 /home/bfw/.emacs.d/.python-environments/i386/bin/jediepcserver
/usr/bin/python2.7 /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/evaluate/compiled/subprocess/__main__.py /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages 2
```
```
(:emacs-version "25.3.1" :jedi-version "0.2.7")
((:version "2.7.15 (default, Oct  6 2018, 14:26:45) \n[GCC 5.4.0 20160603 (Red Hat 5.4.0-6)]" :name "sys" :file nil)
 (:version "0.12.1" :name "jedi" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/sexpdata.pyc"))
```
* After removing the old env and doing a new install there are many processes. A new subprocess is created for every python file visited.
```
% mv ~/.emacs.d/.python-environments  ~/.emacs.d/.python-environments.hide
```
```
M-x jedi:install-server
```
```
/home/bfw/.emacs.d/.python-environments/i386/bin/python2 /home/bfw/.emacs.d/.python-environments/i386/bin/jediepcserver
/home/bfw/.emacs.d/.python-environments/i386/bin/python2 /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/evaluate/compiled/subprocess/__main__.py /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages 2.7.15
/home/bfw/.emacs.d/.python-environments/i386/bin/python2 /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/evaluate/compiled/subprocess/__main__.py /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages 2.7.15
/home/bfw/.emacs.d/.python-environments/i386/bin/python2 /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/evaluate/compiled/subprocess/__main__.py /home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages 2.7.15
```
```
(:emacs-version "25.3.1" :jedi-version "0.2.7")
((:version "2.7.15 (default, Oct  6 2018, 14:26:45) \n[GCC 5.4.0 20160603 (Red Hat 5.4.0-6)]" :name "sys" :file nil)
 (:version "0.13.1" :name "jedi" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/home/bfw/.emacs.d/.python-environments/i386/lib/python2.7/site-packages/sexpdata.pyc"))
```
* *Is this expected behavior?*

**Comment by Yevgnen** [comment] 2018-11-28 04:04
I'm not sure whether [this issue](https://github.com/jorgenschaefer/elpy/issues/1502) is related. But I got so many processes too...

**Comment by immerrr** [comment] 2018-12-06 21:15
I have minimized it to this repro script:
```
import os
from jedi.api import Script
os.environ.pop('VIRTUAL_ENV', None)
for i in range(1000):
    s = Script(source='', line=1, column=0)
    s.completions()
```

The problem is that without `VIRTUAL_ENV` variable set `get_cached_default_environment` never reuses the default environment, because `environment.path` is never `None` and thus [the following condition](https://github.com/davidhalter/jedi/blob/master/jedi/api/environment.py#L194) is never true:
```
    if environment.path != os.environ.get('VIRTUAL_ENV'):
```

**Comment by immerrr** [comment] 2018-12-07 11:59
Duplicate of #1242.

**Comment by davidhalter** [comment] 2018-12-15 18:16
#1238 was merged. Please also continue the discussion in #1242.

**Closed by davidhalter** 2018-12-15 18:16 UTC
