### ISSUE TITLE
Incorrect completitions for multiprocessing module in python3

### ISSUE THREAD

**Issue by XAMeLeOH** [davidhalter/jedi#802] opened 2016-11-09 12:41 UTC
Working with atom's autocomplete-python which uses jedi I've found that there are incorrect suggestions for `multiprocessing` module in `python3`. Here is an example:

    >>> import jedi
    >>> source = '''
    ... import multiprocessing as mp
    ... mp.Pro'''
    >>> script = jedi.Script(source, 3, len('mp.Pro'), 'example.py')
    >>> script.completions()
    [<Completion: process>]

Module actually has `process` package but also it has `Process` class inside of module scope:

    >>> import multiprocessing as mp
    >>> [n for n in mp.__all__ if n.endswith('rocess')]
    ['Process', 'current_process']

Comparing python2's and python3's `multiprocessing` module I've found that they are slightly different. Modern version imports namespace of the default context's namespace:

    globals().update((name, getattr(context._default_context, name))
                 for name in context._default_context.__all__)
    __all__ = context._default_context.__all__

Unfortunately, I don't have any ideas how to resolve this problem or workaround it. Do you have any suggestions?

**Comment by davidhalter** [comment] 2016-11-11 14:47
Duplicate of #432 and others.

**Closed by davidhalter** 2016-11-11 14:47 UTC
