### ISSUE TITLE
CompiledValue' object has no attribute 'string_names

### ISSUE THREAD

**Issue by danzvara** [davidhalter/jedi#1632] opened 2020-07-07 13:01 UTC
Hi all! I encountered the following error when trying to get completions for Tensorflow==1.15 with Jedi==0.17.1. Any idea what could go wrong? I could do a PR that adds `string_names` to the `CompiledValue` object, but I suspect this might have a deeper cause. 

Thanks!

Code:
```
import tensorflow as tf

tf.
```
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/python_jsonrpc_server-0.3.4-py3.7.egg/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python3.7/site-packages/python_jsonrpc_server-0.3.4-py3.7.egg/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python3.7/site-packages/python_jsonrpc_server-0.3.4-py3.7.egg/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Users/daniel-mbp/python-language-server/pyls/python_ls.py", line 345, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Users/daniel-mbp/python-language-server/pyls/python_ls.py", line 259, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/Users/daniel-mbp/python-language-server/pyls/python_ls.py", line 175, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/manager.py", line 335, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/manager.py", line 333, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy-0.13.0-py3.7.egg/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/daniel-mbp/python-language-server/pyls/plugins/jedi_completion.py", line 61, in pyls_completions
    completions = document.jedi_script().complete(**code_position)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/__init__.py", line 275, in complete
    return self._complete(line, column, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/__init__.py", line 283, in _complete
    return completion.complete()
  File "/usr/local/lib/python3.7/site-packages/jedi/api/completion.py", line 172, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/completion.py", line 283, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/usr/local/lib/python3.7/site-packages/jedi/api/completion.py", line 393, in _complete_trailer
    if len(v.string_names) == 1:
AttributeError: 'CompiledValue' object has no attribute 'string_names'
```

**Comment by davidhalter** [comment] 2020-07-12 21:27
Unfortunately I cannot reproduce (on master and 0.17.0). I'm on Ubuntu.

I might close this one if I cannot reproduce.

> I could do a PR that adds string_names to the CompiledValue object, but I suspect this might have a deeper cause.

Exactly. The question is: Why is this not a `CompiledModule` instead of a `CompiledValue`.

**Comment by davidhalter** [comment] 2020-07-17 09:34
I'm closing. I still believe there is an issue, but this issue will get nowhere like this. I guess I'm waiting until someone else has a different reproduction for this, so I can fix it.

Sorry.

**Closed by davidhalter** 2020-07-17 09:34 UTC
