### ISSUE TITLE
Wrong completions for numpy

### ISSUE THREAD

**Issue by mwlodarczak** [davidhalter/jedi#633] opened 2015-10-15 15:58 UTC
Completion works fine for modules from the standard library but if I import, say, numpy and then type "numpy.", I get completions which include things like "re" and "os" and "collections". 

I'm seeing this with jedi 0.9.0 and Python 2.7.9.

**Comment by davidhalter** [comment] 2015-10-16 00:14
This is basically a duplicate of #11.

If we implemented support for `__all__`, this would be possible. However it's really hard to implement it properly.
Therefore I have decided - and I still think this was the correct decision - to just leave those imports in there.

If you want this to change, try to play around with it yourself. I'm glad to assist you, but I have different priorities. Until that happens, this issue stays closed.

**Closed by davidhalter** 2015-10-16 00:14 UTC
