### ISSUE TITLE
Playing nicely with docker

### ISSUE THREAD

**Issue by talwrii** [davidhalter/jedi#1616] opened 2020-06-18 15:12 UTC
Docker is really trendy, so trendy that I'm made (willing comply) with using it for development at work.  What this ends up looking like is that I bind mount a project into docker and run - docker provides the dependencies, the bind mount provides the code. I don't know how common this is is for develoment.

I've made docker play nicely with pylint in emacs (I have a per docker image pylint in the container that I use for syntax checking), but I'm wondering whether I could make jedi run in the same environment as the docker component. Everything works when jumping around "within my project" but issues start occuring when I want to jump into external libraries.

At the moment I deal with this by having identical versions of all the libraries I use within my docker containers on my filesystem, but in practice this is a horrible mistake in understanding caused by a version mismatch waiting to happen and at some point I'm going to start having different versions of libraries in different images. 

Is this something you would be keen on supporting?

An issue that would affect any code that supports this would be that when you jump to an external dependency it doesn't exist on the filesystem but inside a docker container. I think the way that pycharm deals with this is copying out the code from the container and letting you jump to it. Ideally you would also be able to jump around within the code that you have copied out so you would need to keep track of the fact that you are looking at code that comes from within a docker container and work out which container you came from.  I guess the editor could handle this, my understanding is that the way jedi works is that you send it a complete file to look at rather than a filename (presumably so you can work without saving) - so this would work well.

I guess what you could do is have jedi running completely within the docker container, and then have the editor map filenames.

Opinions and pointers to where I might change code?

**Comment by davidhalter** [comment] 2020-06-18 22:33
> Is this something you would be keen on supporting?

The question is probably what that would look like. Jedi is a library and as such shouldn't do a lot of magic. So copying files somewhere is definitely not Jedi's job. Analyzing files in weird folders, maybe.

So I guess I would need a more concrete proposal before you dive into the code. If you have a simple way to access files inside a docker container, you can probably just do that with Jedi's IO classes. But it's probably not going to be easy.

With a concrete proposal I don't mean code examples, I mean something like "Jedi should ideally lookup an `import bar` with `docker <some command> <id> /foo/bar.py`. So I need a concept that makes sense to discuss.

**Comment by talwrii** [comment] 2020-06-19 00:07
Thanks for your reply.

> So I need a concept that makes sense to discuss.

I'm an emacs user btw (might be relevant for what follows). I'm not particularly familiar with vim's scripting language or how jedi works within vim. Given what follows, it might be better to move this into `emacs-jedi` but I suspect it might make sense to think how this might work in an editor-invariant fashion.

Here is an initial proposal where the editor does all the work:

* A separate jedi server is spawned for each docker image (potentially achieved via an optional hook that returns a command to run jedi for each file. Each command would identify a distinct jedi instance. This could be used for virtualenv also).
* Running within docker, jedi returns the path to a docker file.
* A translation layer exists that maps a docker path back to a system path. Again this might like to be a hook, or it might be a list of "prefix-mappings" like ("/app" -> "").  Perhaps docker paths could be represented as "docker:/usr/lib/"
* A "jedi-open" command in the editor that knows how to open these docker paths. There isn't really an easy way to "mount" docker images, but this could be doing using `docker cp`. I would probably dump these file in e.g. /tmp/$ID/full path. We could need the command that finds an image to look at $ID and return the correct command.

Thining about how this might be moved into jedi:

* Instead of running multiple jedis one could "teach" jedi to run different python commands (e.g `docker -v /bah/blah python3`). I don't know if jedi is keeping any state to improve performance. Perhaps we could optionally pass a python command when we run jedi. This would remove the need to run mutiple jedis, instead jedi would do its work in a separate python (either within a virtualenv or a docker)
* When we create the mirror files in `/tmp/$ID/` we could keep some metadata at the top level saying how jedi should run python. I guess if jedi knows how to run python, we could reuse this python to extract files from within the docker container. We would then extend jedi to support a "copy file" command or perhaps a mirror-file command that creates our /tmp/$ID/directory. I'm not sure how jedi would know which $ID to write to. I guess the editor could still keep track of this ID
* Perhaps if we send jedi a file in `/tmp/$ID` it could remember which python to use (perhaps looking it up in ID)

With this second, smaller proposal. The only think the editor would have to do is work out a python command to (optionally) send for each file, and mapping files. I guess we could also pass a set of mappings into jedi and have it return the appropriate files. 

Making this a bit less waffley...

* One could have a call goto-def {file_contents:str, python_command: str (e.g. docker run -v /blah/bah python3), path_mappings: {str: str}} . Jedi will then either return a local path (if the path returned is within the path_mappings, or it will map the file locally
* goto-def coud be extended so that if is given a "mapped" file, it works out which python_command to use.

**Comment by davidhalter** [comment] 2020-06-19 09:56
> * A translation layer exists that maps a docker path back to a system path. Again this might like to be a hook, or it might be a list of "prefix-mappings" like ("/app" -> "").  Perhaps docker paths could be represented as "docker:/usr/lib/"

This is also how I would imagine it working. The problem is writing the translation layer and actually getting the data out of the container. The alternative is to run Jedi inside the container, which is also possible, but then no changes need to be made here.

----------------

About the rest of the ideas, I just have to say that they are way too much written from an emacs perspective. Some things I simply don't understand. Apart from copying the files to the outside of the container, there's really not a lot that Jedi could do that would just easily work. So I guess I'm closing here.

IMO docker support would be cool, but the more I'm reading, the more I understand that it's not the idea to access files inside of docker from the outside. This is exactly because docker wants isolation between processes. So there's not a lot Jedi could do here. Editors can of course hack around that kind of stuff, but even then I think it's a bad idea.

**Closed** 2020-06-19 09:59 UTC

**Comment by talwrii** [comment] 2020-06-19 18:07
Cool cool. Thanks for looking into this anyway. 

I'll check back if I have a go at implementing this (in jedi itself or jedi-emacs).

A working prototype might be a little easier to understand than my thinking.

**Comment by davidhalter** [comment] 2020-06-19 18:29
Yeah, if there's anything Jedi can do so it works better, feel free to keep the discussion going. I just think that other than copying, there's nothing that Jedi could really do that would help.
