### ISSUE TITLE
ValueError exception trying to get full_name of completion

### ISSUE THREAD

**Issue by dsedivec** [davidhalter/jedi#907] opened 2017-04-09 18:10 UTC
Hi!  Jedi seems to have a problem with the `full_name` of a completion on `os.path`.  Test script, tested against master (8bdf7e32) as of this writing:

```python
from jedi.api import Script
completions = Script(source="import os.path\nos.path").completions()
print "completions:", repr(completions)
print completions[0].full_name
```

Output when run with Python 2.7 from MacPorts on OS X 10.11.6:

```
$ PYTHONPATH=$PWD python2.7 test_case.py
completions: [<Completion: path>, <Completion: pathconf>, <Completion: pathconf_names>, <Completion: pathsep>]
Traceback (most recent call last):
  File "test_case.py", line 4, in <module>
    print completions[0].full_name
  File "/private/tmp/jedi/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/private/tmp/jedi/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/private/tmp/jedi/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: need more than 0 values to unpack
```

I came across this through using Jedi via [anaconda-mode](https://github.com/proofit404/anaconda-mode/blob/master/anaconda_mode.py#L48) in Emacs.

Thanks for writing and maintaining Jedi!

**Comment by davidhalter** [comment] 2017-09-13 08:20
Duplicate of #907

**Closed by davidhalter** 2017-09-13 08:20 UTC

**Comment by dsedivec** [comment] 2017-09-14 01:39
> Duplicate of #907

Sorry, I don't understand, #907 cannot be a duplicate of itself, right?  Presumably you meant another issue?

**Comment by davidhalter** [comment] 2017-09-14 07:01
Sorry that was stupid of me. I meant of course #873.
