### ISSUE TITLE
Python jedi intellisense is stuck on loading  in VSCODE 

### ISSUE THREAD

**Issue by 1470391328** [davidhalter/jedi#1534] opened 2020-04-01 07:19 UTC
Some function documents that are not recognized by Jedi will cause Jedi to be stuck in the loading state for a long time. expecially for 'pyi' file.

For example , If you write the code, “from PyQt5.QtWidgets import QApplication” ，and through the shortcut key to view the function document of QApplication, Jedi will be stuck in the loading state. Of course, this problem is not limited to pyqt5 module. Some functions in other modules that are not recognized by Jedi will cause the same problem.

Here is a GIF demo file：

![GIF 2020-4-1 11-06-34](https://user-images.githubusercontent.com/33288114/78109624-25378500-742c-11ea-9084-a43b091beb8d.gif)

**Comment by davidhalter** [comment] 2020-04-01 11:19
I don't understand at all. I'm not working with VSCode and also don't speak Chinese. You should probably post your issue in the VSCode Python tracker first. If it is really an issue with Jedi, it would be nice if you worked with the Jedi API to reproduce your issue with Jedi only.

I'm closing because of this. I'm happy to reopen if you provide something along the lines of `jedi.Script('from PyQt5.QtWidgets import QApplication').goto()`, but at the moment I do not know what you are talking about.

**Closed by davidhalter** 2020-04-01 11:19 UTC
