### ISSUE TITLE
Support option for virtual/database filesystems

### ISSUE THREAD

**Issue by scarab5q** [davidhalter/jedi#1419] opened 2019-10-04 11:29 UTC
I think this might relate to #1059 but I was thinking about Amazons's S3, Microsoft's vfs for git or even oracle's dbfs and how that might start becoming a more common thing within everyday developers. My thought is that Jedi wouldn't necessarily support those but also even if it did given that vfs for git is explicitly supposed to be for REALLY large projects and as has been mentioned in many issues there are issues with Jedi working with large projects. 

There are a few things that I think that are necessary for Jedi to really work on that kind of scale:

1. have an option for jedi to store the objects that parso returns into a database (such as SQLite) which could then be indexed and read from in a much quicker way.
2. similarly have an option to read from an already existing database that could could be pointed to by the user
3. allow plugins for different databases
4. have an option to read files from a path or a filesystem that the user could supply with something like [pyfilesystem2](https://github.com/PyFilesystem/pyfilesystem2)

I think the database thing could be done by changing the stuff in cache to point towards a database rather than the cache_directory on the cache_path. Furthermore the pyfilesystem thing could be implemented by rewriting jedi/inference/sys_path.py to use it. Furthermore this may be  a good idea anyway given that the pyfilesystem api is really nice to work with. Having said all of this I will freely admit that I don't have the best understanding of the jedi codebase and therefore I might have missed something. I'm currently trying to figure out how the

 Regardless of whether my specific ideas on implementation are feasible, I would be very happy to work on adding database functionality into jedi would be really useful for speed on really large projects. I'd also be interested adding the functionality to add additional filesystems to jedi aswell.

**Comment by davidhalter** [comment] 2019-10-07 20:42
> 1. have an option for jedi to store the objects that parso returns into a database (such as SQLite) which could then be indexed and read from in a much quicker way.

That's not the issue. The index would probably cover way more than this. It's easier to do this as an in memory structure (with optional offloading to the filesystem if it gets too big). The goal of using a database is caching of inference results, which is basically a big graph. The hard part is doing the invalidation of that graph.

> 4. have an option to read files from a path or a filesystem that the user could supply with something like pyfilesystem2

This already exists in a way internally (search for FileIO). It probably wouldn't be too hard to make these things more public, but at the same time it doesn't really help. People should probably just start using `sys.meta_path` for this. And once people work properly with that we can just integrate that in Jedi. It's pretty much how you would want to do an import system in the "cloud" anyway. 

However also note that putting your source code into the cloud is an extremely dumb idea in the first place. But if people really want that `sys.meta_path` is probably the way. This could work with Jedi without issues, if you configure it the right way (using `InterpreterEnvironment`) for example.

> Furthermore the pyfilesystem thing could be implemented by rewriting jedi/inference/sys_path.py to use it. 

The biggest problem is that the heavy lifting is done by `importlib`, so applying something like `pyfilesystem` would imply rewriting a lot of `importlib`, which is a lot of work. Therefore it's probably way easier to just write something that works with `sys.meta_path`. Having a `MetaPathFinder` implemented makes sense anyway, because at that point a normal `import foo.bar` works, even if it loads the data from somewhere not in the file system.

> Regardless of whether my specific ideas on implementation are feasible, I would be very happy to work on adding database functionality into jedi would be really useful for speed on really large projects.



> I'd also be interested adding the functionality to add additional filesystems to jedi aswell.

Feel free to do that. It will probably be slower and cause other issues, but it can work. Just implement a `MetaPathFinder` and use an `InterpreterEnvironment`. Play around with it. If it works well we can add it a `meta_path` argument to the Jedi API to make it possible to deal with it in a better way. I'm happy to assist if you encounter issues.

**Comment by davidhalter** [comment] 2019-10-07 20:48
> 1. have an option for jedi to store the objects that parso returns into a database (such as SQLite) which could then be indexed and read from in a much quicker way.

That's not the issue. The index would probably cover way more than this. It's easier to do this as an in memory structure (with optional offloading to the filesystem if it gets too big). The goal of using a database is caching of inference results, which is basically a big graph. The hard part is doing the invalidation of that graph.

> 4. have an option to read files from a path or a filesystem that the user could supply with something like pyfilesystem2

This already exists in a way internally (search for FileIO). It probably wouldn't be too hard to make these things more public, but at the same time it doesn't really help. People should probably just start using `sys.meta_path` for this. And once people work properly with that we can just integrate that in Jedi. It's pretty much how you would want to do an import system in the "cloud" anyway. 

However also note that putting your source code into the cloud is an extremely dumb idea in the first place. But if people really want that `sys.meta_path` is probably the way. This could work with Jedi without issues, if you configure it the right way (using `InterpreterEnvironment`) for example.

> Furthermore the pyfilesystem thing could be implemented by rewriting jedi/inference/sys_path.py to use it. 

The biggest problem is that the heavy lifting is done by `importlib`, so applying something like `pyfilesystem` would imply rewriting a lot of `importlib`, which is a lot of work. Therefore it's probably way easier to just write something that works with `sys.meta_path`. Having a `MetaPathFinder` implemented makes sense anyway, because at that point a normal `import foo.bar` works, even if it loads the data from somewhere not in the file system.

> Regardless of whether my specific ideas on implementation are feasible, I would be very happy to work on adding database functionality into jedi would be really useful for speed on really large projects.

I'm very happy to have help with that, but just note that this is probably one of the hardest thing to do. There's two things I consider really hard (and I'm currently doing research on those). Cache invalidation of inference results and incremental parsing with immutable data structures. The first one is essentially the problem you want to tackle.

If you have proposals or ideas I'm open to hear them. Essentially caching boils down to save results from type inference to a database and then removing them again, if a user changes a file. The problem is usually that you want to invalidate as much as you need to invalidate, but not more. This is the hard part. It's just really hard to know what actually changed and what didn't.

> I'd also be interested adding the functionality to add additional filesystems to jedi aswell.

Feel free to do that. It will probably be slower and cause other issues, but it can work. Just implement a `MetaPathFinder` and use an `InterpreterEnvironment`. Play around with it. If it works well we can add it a `meta_path` argument to the Jedi API to make it possible to deal with it in a better way. I'm happy to assist if you encounter issues.

**Comment by scarab5q** [comment] 2019-12-05 18:01
Sorry I've not replied in a while I still want to do this. In terms of the cache system have you seen [diskcache?](https://github.com/grantjenks/python-diskcache) It's a pure python implementation of a disk-caching system that can also link to a database, it claims to have good performance and is also written in pure python. Adding dependencies to Jedi I assume is not something that you would like to do and I'm not necessarily suggesting that. However, this is at least a reference implementation for how to go about making something similar for jedi. I'll play around with this and report back with my findings/

**Comment by davidhalter** [comment] 2019-12-22 17:42
I'm closing this, because I don't see this happening very soon. I also don't see a lot of value for all current Jedi users. This might be interesting for some companies that do weird stuff with cloud backed storage or whatever, but I would probably only work on that paid.

@scarab5q Feel free to ask further questions. I'm closing this, because I really don't think that this helps current Jedi users. I personally won't invest a lot of time into this, but I'm open if you create some pull requests.

**Closed by davidhalter** 2019-12-22 17:42 UTC
Labels: discussion
