### ISSUE TITLE
Completions for lambda arguments

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1643] opened 2020-07-26 11:04 UTC
It would be awesome if Jedi offered completions within lambdas when they're passed as arguments.

For example:
``` python
things = ['a', 'A', 'b']
sorted(
    things,
    lambda x: x.<here>
)
```

Especially where the function being called (`sorted` in the above) is typed, Jedi should be able to provide some useful completions. `mypy` does similar inference and does check such lambdas, so this feels possible. I'm guessing that it could be quite hard without annotations, though might still be possible.

**Comment by PeterJCLaw** [comment] 2020-07-26 11:05
This feels like it might have some overlap with #1640, though I'm not sure.

**Comment by davidhalter** [comment] 2020-07-26 11:27
I think I have rejected this before here: https://github.com/davidhalter/jedi/issues/1523. However if you want to do it, you seem to know a lot of details about Jedi already, so why not. It's just definitely not a beginner issue. I'm definitely not going to implement this :).

> mypy does similar inference and does check such lambdas, so this feels possible.

Yes, Jedi probably also understands this kind of stuff. The problem is that with completions you always have very broken code that somehow needs to be understood. For example in your case it could be:

```
sorted(
    things,
    lambda x: x.
```

The problem here is that you kind of need to deal with a broken sorted function call, an incomplete lambda and an incomplete `x.`. I'm of course not saying that this is impossible, it's very much possible. It's just annoying to deal with all the edge cases :).

**Comment by PeterJCLaw** [comment] 2020-07-26 12:01
Ah, sorry, missed that previous issue.

Personally I very much tend to insert the closing paren when creating new function calls (or rather, my editor does for me), plus of course editing existing code would already have it there. I think there's a lot of value to be had even from this only working where the closing paren is present.

I'm happy to pick this up at some point, though likely not for a little while.

**Comment by PeterJCLaw** [comment] 2022-06-11 12:40
Unassigning as I've not found time for this and realistically I'm not sure I'm going to any time soon. I've enjoyed working on Jedi, though recently my focus has been elsewhere.

**Comment by davidhalter** [comment] 2022-06-11 22:06
I guess I would close this one then. (see my reasoning above).

**Closed by davidhalter** 2022-06-11 22:06 UTC
Labels: feature, help-wanted
