### ISSUE TITLE
wrong docstring for wrapped function

### ISSUE THREAD

**Issue by mchwalisz** [davidhalter/jedi#906] opened 2017-04-06 14:18 UTC
## Expected Behaviour
I would expect that jedi shows the correct docstring and function reference for wrapped functions.
In the same scenario jupyter notebook works correctly:

![jupyter notebook](https://cloud.githubusercontent.com/assets/2182186/24757830/a34fe8a4-1ae0-11e7-8608-99e3b88638b9.png)

## Actual Behaviour
![jedi](https://cloud.githubusercontent.com/assets/2182186/24757418/7e91c272-1adf-11e7-953c-3231cd8c8eaa.png)

Shows wrong wrapping function reference. Based on Sublime text and anaconda DamnWidget/anaconda#644

## Steps to Reproduce

```python
from functools import wraps


def decorator(name=None):
    """wrapper doc string"""
    def _decorate(func):
        @wraps(func)
        def wrapper():
            print(name)
            return func()
        return wrapper
    return _decorate


@decorator('testing')
def wrap_user():
    """Nice doc string"""
    print('doing stuff...')

print(wrap_user.__name__)
print(wrap_user.__doc__)
wrap_user()
```
Execution results in:

```
wrap_user
Nice doc string
testing
doing stuff...
```
which is good name and docstring.

**Comment by davidhalter** [comment] 2017-04-06 18:16
I think the jupyter notebook has it way easier to show the correct signatures, because it can actually look at evaluated code. But in any case I think we should implement this, too.

**Comment by mchwalisz** [comment] 2017-04-07 06:48
I see the point about jupyter, didn't realize that it actually needs to run the code before showing tooltips.
At the beginning I thought the bug only relates to decorators with arguments but it looks like all decorators cause problems for jedi. Following is even simpler example.

Still it is worth looking into `functools.wraps`, as it is Python way to help with decorated function names.

```python
from functools import wraps
def simple_decorator(func):
    'simple decorator docstring'
    @wraps(func)
    def _wrapper():
        '_wrapper docstring'
        print('here')
        return func()
    return _wrapper

@simple_decorator
def nice_func():
    'nice func docstring'
    print('bar')

print(nice_func.__name__)
print(nice_func.__doc__)
```

Finally, evaluating code might potentially be very harmful.

**Comment by davidhalter** [comment] 2017-04-25 20:09
Jedi does not evaluate code. And you're right trying to statically analyze code and check for wraps calls would probably make sense.

**Comment by malmaud** [comment] 2018-06-20 15:52
First, thank you for the great work on Jedi! 
I wanted to ask if there any plans to investigate implementing this. It would be great if eg VSCode and other IDEs using Jedi could show docstrings and function signatures for decorated methods using `@wraps`. Some libraries decorate the bulk of their APIs, really leading to a suboptimal IDE experience when using them, given this current limitation.

**Comment by davidhalter** [comment] 2018-06-21 17:49
@malmaud There is currently no plan to that, but I'm planning on improving `*args`/`**kwargs` support for decorators, so people can see what they are actually pushing into a function. That should happen pretty soon.

Since you reminded me about this issue, I might also take a look at this in the same process (even if people are not using wraps, people that are using IDE's are usually happy enough with good heuristics).

**Comment by malmaud** [comment] 2018-06-21 18:32
Ah, great. Any solution that allows IDEs to show docstrings and/or original arguments of decorated functions, however heuristically, would be awesome.

**Comment by timmy8526** [comment] 2019-02-26 02:36
Is there any update? This causes the IDE shows incorrect arguments options if func is using decorator ..
Or is there any temporary workaround to make it work now?

For example:

1. Without decorator, the auto completion works properly.
   ![image](https://user-images.githubusercontent.com/13176540/53383236-e5dd7000-39b1-11e9-81dc-fc138611c534.png)
2. With decorator, the auto completion will be overwritten by decorator's passing arguments.
   ![image](https://user-images.githubusercontent.com/13176540/53383271-01e11180-39b2-11e9-88be-9f43f0b1b142.png)

**Comment by Davide-sd** [comment] 2019-04-30 15:04
Any news on a possible fix?

**Comment by davidhalter** [comment] 2019-05-02 23:28
If you want to push an issue, just add a :+1: on top, I occasionally sort by those.

Comments are just annoying and don't really help you guys.

**Comment by bet4it** [comment] 2019-05-06 14:04
If I have a file `/tmp/docstr.py`:
``` python
class B:
    """This is what I get"""
    def __init__(self):
        pass

class A:
    def __init__(self):
        pass

    @property
    def func(self):
        """This is what I want"""
        return B()

a = A()
a.f
```
and run following code:
```python
import jedi
with open('/tmp/docstr.py') as f:
    s = jedi.Script(f.read(), 16, 3)
    comps = s.completions()
    print(comps[0].docstring())
```
I will get the docstring of `B` rather than `func`.

I think this example has the same cause with this issue?

**Comment by davidhalter** [comment] 2019-07-21 10:20
I didn't realize how easy this could have been. Sorry for that.

Anyways, it's fixed now.

**Closed** 2019-07-21 10:20 UTC
Labels: feature

**Comment by wtfzambo** [comment] 2020-06-23 14:29
I seem to have incurred in this bug again.

I'm using ST3 with Anaconda plugin. Normally showing docstrings works perfectly, except, it seems for functions that are wrapped in a decorator, such as this (see screen):

![image](https://user-images.githubusercontent.com/47462792/85416250-858f1c00-b56e-11ea-84fc-f4c32fb4d2d4.png)

Any idea how to fix this?

For the record, st is `streamlit` package.

**Comment by davidhalter** [comment] 2020-06-23 22:45
@wtfzambo Please give me a complete example that I can reproduce. You should probably also open a new issue, because this issue was definitely fixed (it's actively tested).

**Comment by wtfzambo** [comment] 2020-06-24 00:36
@davidhalter ok I'll open a new issue
