### ISSUE TITLE
API Exception: {'type': 'AttributeError', 'args': ('lambda is not named.',), 'message': 'lambda is not named.'}

### ISSUE THREAD

**Issue by gatesn** [davidhalter/jedi#1070] opened 2018-03-25 14:50 UTC
As per this ticket in PYLS: https://github.com/palantir/python-language-server/issues/231

```
>>> 
LSP:  --> textDocument/definition
2018-01-18 14:58:14,907 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'AttributeError', 'args': ('lambda is not named.',), 'message': 'lambda is not named.'}:
Traceback (most recent call last)::
File "F:\Python\lib\site-packages\jsonrpc\manager.py", line 112, in _get_responses:
result = method(*request.args, **request.kwargs):
File "d:\python-language-server\pyls\dispatcher.py", line 19, in wrapped:
return func(*args, **kwargs):
File "d:\python-language-server\pyls\python_ls.py", line 157, in m_text_document__definition:
return self.definitions(textDocument['uri'], position):
File "d:\python-language-server\pyls\python_ls.py", line 92, in definitions:
return flatten(self._hook('pyls_definitions', doc_uri, position=position)):
File "d:\python-language-server\pyls\python_ls.py", line 41, in _hook:
return hook(config=self.config, workspace=self.workspace, document=doc, **kwargs):
File "F:\Python\lib\site-packages\pluggy\__init__.py", line 617, in __call__:
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs):
File "F:\Python\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec:
return self._inner_hookexec(hook, methods, kwargs):
File "F:\Python\lib\site-packages\pluggy\__init__.py", line 182, in __call__:
return outcome.get_result():
File "F:\Python\lib\site-packages\pluggy\callers.py", line 76, in get_result:
raise ex[1].with_traceback(ex[2]):
File "F:\Python\lib\site-packages\pluggy\callers.py", line 48, in from_call:
result = func():
File "F:\Python\lib\site-packages\pluggy\__init__.py", line 180, in <lambda>:
outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs)):
File "F:\Python\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>:
firstresult=hook.spec_opts.get('firstresult'),:
File "F:\Python\lib\site-packages\pluggy\callers.py", line 201, in _multicall:
return outcome.get_result():
File "F:\Python\lib\site-packages\pluggy\callers.py", line 76, in get_result:
raise ex[1].with_traceback(ex[2]):
File "F:\Python\lib\site-packages\pluggy\callers.py", line 180, in _multicall:
res = hook_impl.function(*args):
File "d:\python-language-server\pyls\plugins\definition.py", line 10, in pyls_definitions:
definitions = document.jedi_script(position).goto_assignments():
File "F:\Python\lib\site-packages\jedi\api\__init__.py", line 212, in goto_assignments:
names = list(self._evaluator.goto(context, tree_name)):
File "F:\Python\lib\site-packages\jedi\evaluate\__init__.py", line 280, in goto:
values = helpers.evaluate_call_of_leaf(context, name, cut_own_trailer=True):
File "F:\Python\lib\site-packages\jedi\evaluate\helpers.py", line 99, in evaluate_call_of_leaf:
values = context.eval_node(base):
File "F:\Python\lib\site-packages\jedi\evaluate\base_context.py", line 123, in eval_node:
return self.evaluator.eval_element(self, node):
File "F:\Python\lib\site-packages\jedi\evaluate\__init__.py", line 179, in eval_element:
return self._eval_element_if_evaluated(context, element):
File "F:\Python\lib\site-packages\jedi\evaluate\__init__.py", line 191, in _eval_element_if_evaluated:
return self._eval_element_cached(context, element):
File "F:\Python\lib\site-packages\jedi\evaluate\cache.py", line 40, in wrapper:
rv = function(obj, *args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\__init__.py", line 195, in _eval_element_cached:
return eval_node(context, element):
File "F:\Python\lib\site-packages\jedi\debug.py", line 79, in wrapper:
return func(*args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\syntax_tree.py", line 46, in wrapper:
return func(context, *args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\syntax_tree.py", line 58, in eval_node:
return eval_atom(context, element):
File "F:\Python\lib\site-packages\jedi\evaluate\syntax_tree.py", line 172, in eval_atom:
search_global=True:
File "F:\Python\lib\site-packages\jedi\_compatibility.py", line 204, in <lambda>:
return lambda *args, **kwargs: self.func(obj, *args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\base_context.py", line 140, in py__getattribute__:
return f.find(filters, attribute_lookup=not search_global):
File "F:\Python\lib\site-packages\jedi\debug.py", line 79, in wrapper:
return func(*args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\finder.py", line 64, in find:
types = self._names_to_types(names, attribute_lookup):
File "F:\Python\lib\site-packages\jedi\evaluate\finder.py", line 157, in _names_to_types:
contexts = ContextSet.from_sets(name.infer() for name in names):
File "F:\Python\lib\site-packages\jedi\common\context.py", line 34, in from_sets:
sets = list(sets):
File "F:\Python\lib\site-packages\jedi\evaluate\finder.py", line 157, in <genexpr>:
contexts = ContextSet.from_sets(name.infer() for name in names):
File "F:\Python\lib\site-packages\jedi\evaluate\filters.py", line 118, in infer:
return self.get_param().infer():
File "F:\Python\lib\site-packages\jedi\evaluate\filters.py", line 121, in get_param:
params = self.parent_context.get_params():
File "F:\Python\lib\site-packages\jedi\evaluate\cache.py", line 40, in wrapper:
rv = function(obj, *args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\context\function.py", line 226, in get_params:
return self.var_args.get_params(self):
File "F:\Python\lib\site-packages\jedi\evaluate\arguments.py", line 79, in get_params:
execution_context.tree_node:
File "F:\Python\lib\site-packages\jedi\debug.py", line 79, in wrapper:
return func(*args, **kwargs):
File "F:\Python\lib\site-packages\jedi\evaluate\dynamic.py", line 76, in search_params:
debug.dbg('Dynamic param search in %s.', funcdef.name.value, color='MAGENTA'):
File "F:\Python\lib\site-packages\parso\python\tree.py", line 654, in name:
raise AttributeError("lambda is not named."):
AttributeError: lambda is not named.:
```

**Comment by davidhalter** [comment] 2018-03-25 21:55
Thanks for reporting this one. It should be fixed and lambda param completions better.

**Comment by Peder2911** [comment] 2021-04-30 09:23
Hey! Just hit this bug again.
Jedi version 0.18.0
Code:
```
shapes = compose(
      curry(date_filtered)(start_date,end_date),
      curry(user_only)(user),
      lambda q: q.query(models.Shape.shape)
   )(session).all()
```

**Comment by davidhalter** [comment] 2021-11-16 23:56
@Peder2911 Can you send us a traceback? It's pretty hard to understand what happens in your case. It's probably a different bug than the original one.

**Comment by Peder2911** [comment] 2021-11-22 08:32
Hey! Thanks for following up. I am unable to reproduce with Jedi 0.18.1, but I'll let you know if it happens again.

**Comment by davidhalter** [comment] 2021-11-23 21:36
I'm going to close for now. Happy to reopen if it actually still exists :)

**Closed by davidhalter** 2021-11-23 21:36 UTC
Labels: bug
