### ISSUE TITLE
pygame methods arguments popup not always working (python3.6 / pygame / linux)

### ISSUE THREAD

**Issue by nsklaus** [davidhalter/jedi#967] opened 2017-10-14 10:18 UTC
Hi,
i'm trying to solve a problem i have, when using sublimetext3 (st3) for developing pygame projects, on linux. this problem i have showed itself when using anaconda-st3 and pyls too (python-language-server for st3). both of these projects use jedi.
so i suspect the problem might come from jedi itself. in an attempt to pinpoint the root cause i'm posting here too.

here's the issue as i posted on anadonda-st3 github:
https://github.com/DamnWidget/anaconda/issues/712
and on st3 forum:
https://forum.sublimetext.com/t/st3-to-shows-python-methods-arguments/32568

as you can see, some methods do get correct popups (showing arguments)
while some other do not.

```
pygame <-- popup: pygame is a set of python modules designed for writing games ..
pygame.draw <-- popup: draw = MissingModule("draw", geterror(), 1)
pygame.draw.rect <-- popup: no description available
pygame.Rect <-- popup: rect(left, top, width, height) -> rect
```

i've tried this using ubuntu 17.04 and now i'm on 17.10.
the fact that i can run my pygame projects from shell and from st3 and that i'm getting some popups to show up, suggest everything should be installed correctly.
i do not understand why some popup shows up while some other don't ?
is anyone else experiencing this, or is it just me ?

thanks

**Comment by davidhalter** [comment] 2017-10-14 11:57
Jedi doesn't really understand `import pygame.draw`. That's basically the root issue of this problem. Jedi doesn't work because draw is defined in the except clause and that's what it understands.

There are possible solution for this issue, but it won't happen very soon. Basically I think that pygame's MissingModule is just stupid and they should change their code.

Closing, because a duplicate of #769.

**Closed by davidhalter** 2017-10-14 11:57 UTC
