### ISSUE TITLE
No completion for logger when name is used with logging.getLogger

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#608] opened 2015-07-08 15:13 UTC
When using a name with `logging.getLogger`, Jedi won't complete the `logger` object then:

TEST CASE:

    import logging
    logger = logging.getLogger("foo")
    logger.

Leaving out the name (`"foo"`) works.

The `getLogger` method looks like this (Python 3.4.3):

    def getLogger(name=None):
        """
        Return a logger with the specified name, creating it if necessary.

        If no name is specified, return the root logger.
        """
        if name:
            return Logger.manager.getLogger(name)
        else:
            return root

**Comment by davidhalter** [comment] 2015-07-12 15:38
We would have to understand `Logger.manager.getLogger(name)`.

Jedi doesn't understand the following files in logging:

```
Logger.root = root                   
Logger.manager = Manager(Logger.root)
```

When the name is defined, Jedi only evaluates the first branch. This happens to improve Jedi's type inference precision. It's not a performance optimization. 

It's basically a duplicate of #301. I'm closing.

**Closed by davidhalter** 2015-07-12 15:38 UTC
