### ISSUE TITLE
Completions not working for tornado.log.gen_log.

### ISSUE THREAD

**Issue by ericsnowcurrently** [davidhalter/jedi#1189] opened 2018-07-31 18:28 UTC
One of our (vscode-python) users [reported an issue](https://github.com/Microsoft/vscode-python/issues/2102) with auto-complete for `tornado.log.gen_log`.  Here's the code:

    from tornado.log import gen_log
    gen_log.

...which results with nothing.

Note that `tornado` and `tornado.log` work fine, and that `tornado.log.gen_log` is a "RootLogger" object.

**Comment by ericsnowcurrently** [comment] 2018-07-31 18:29
@chen19901225

**Comment by davidhalter** [comment] 2018-07-31 21:56
I realize where this is coming from. This is caused by a Jedi feature that detects if branches and removes results from branches that are guaranteed to never be executed. This is normally a very cool and helpful feature, but might hurt you at some points as well.

The fix for this is #1096, which I'm currently working on. With typeshed a lot of these standard lib things will work better - obviously.

It already works for me again on a local branch where I have typeshed partially working. Just give me a few weeks. :)

**Comment by ericsnowcurrently** [comment] 2018-07-31 22:10
No worries.  Thanks for working on this!

**Comment by davidhalter** [comment] 2019-06-21 22:55
Should be fixed in 0.14.0

**Closed by davidhalter** 2019-06-21 22:55 UTC
Labels: bug
