### ISSUE TITLE
Completion for dictionaries?

### ISSUE THREAD

**Issue by smithsp** [davidhalter/jedi#1244] opened 2018-10-27 09:35 UTC
Consider
```python
>>> import jedi
>>> foo = {}
>>> foo['bar'] = {}
>>> foo['bar']['key'] = 10
>>> i = jedi.Interpreter("foo['bar']['k",[foo])
>>> print i.completions()
[<Completion: KeyboardInterrupt>, <Completion: KeyError>]
>>> i2 = jedi.Interpreter("foo['bar']['k",[foo['bar']])
>>> print i2.completions()
[<Completion: key>, <Completion: KeyboardInterrupt>, <Completion: KeyError>]
```
Why does `i.completions()` include `KeyError` and `KeyboardInterrupt`?  From `i`, how can I detect that I am in a `__getitem__` context and call `jedi.Interpreter` with the correct namespace, as in `i2`?
I tried to search the issues, and didn't see this asked.  I also searched the documentation and didn't see this explicitly excluded as an application of `jedi`, although I may have misunderstood some terminology.

**Comment by davidhalter** [comment] 2018-10-27 09:45
I think what you're searching for is https://github.com/davidhalter/jedi/issues/951. I'm closing this as a duplicate.

**Closed by davidhalter** 2018-10-27 09:45 UTC

**Comment by davidhalter** [comment] 2018-10-27 12:29
I have not tried that yet, but this is definitely possible. However it's currently not part of the Jedi API. 

In case you want to know how we would implement that in Jedi, it goes a bit like this:
We would probably do it a bit similar to the way how `foo.` is handled. In this case we would just check if there's a `foo[` start and then check for dictionary keys. The problem is just that at the moment we don't really "know" what dictionary keys were set as a side effect. This means that we don't know that somewhere in the code `foo['x'] = 3` was set. This would be the hard part.

**Comment by smithsp** [comment] 2018-10-29 18:30
@davidhalter Perhaps for static analysis, you would need to know `foo['x'] = 3` was evaluated somewhere previously, but in the `Interpreter` instance, I just want to be able to give the right dictionary as a namespace, and it seems to be able to get the keys anyway.  I am looking into the `parso` library.
