### ISSUE TITLE
error in process filter: Error from RPC: "[Errno 2] No such file or directory: 'setuptools/__init__.py'"

### ISSUE THREAD

**Issue by shiquanwang** [davidhalter/jedi#394] opened 2014-04-03 04:54 UTC
I'm using `jedi` + `elpy` in `Emacs`.
My Python environment is installed with `miniconda3`.

When writing up `setup.py` for a package, the error:
`error in process filter: Error from RPC: "[Errno 2] No such file or directory: 'setuptools/__init__.py'"`
came out.

Below is `ls setuptools*` under `~/miniconda3/lib/python3.3/site-packages/`:
```bash
sqwang@sqwang-Z820:~$ ls ~/miniconda3/lib/python3.3/site-packages/setuptools*
/home/sqwang/miniconda3/lib/python3.3/site-packages/setuptools-3.1-py3.3.egg
/home/sqwang/miniconda3/lib/python3.3/site-packages/setuptools.pth
```
So no `setuptools` folder nor `__init__.py` file under it.

**Comment by davidhalter** [comment] 2015-03-25 11:36
Any news? If you're not working on a way to reproduce this one, I'm going to close it, because I certainly cannot.

It might have been fixed along the line as well, so please try again.

**Closed** 2015-04-09 14:29 UTC
Labels: bug
