### ISSUE TITLE
Autocomplete not working with relative import 

### ISSUE THREAD

**Issue by erezsh** [davidhalter/jedi#1463] opened 2019-12-28 01:50 UTC
Hi, I'm using Jedi 0.15.2 in vscode, Python 3.8, and I can't get the autocomplete to work for modules that are imported using `from . import ...`

For example, I put in a directory called `bug` two files. 
```python
# hello.py
def f1(x: int, b: str):
    pass
```
and
```python
# test.py
from . import hello
print(hello.f1)
```

and of course an empty `__init__.py` file.

I can run `test.py` and get the correct result, so I know this is valid python:
```bash
$ python -m bug.test
<function f1 at 0x000002907C518B80>
```

But if I type in `test.py` the text `hello.`, I will not get autocomplete to suggest `f1`. Also, typing `hello.f1` doesn't bring up the autocomplete for f1's arguments. Also "Go To Definition" doesn't work on f1.

BUT, if I add `import hello` to `test.py`, suddenly all three things work.

Can you please tell me what's I'm doing wrong, and how to resolve it?

Thanks

**Comment by erezsh** [comment] 2019-12-28 01:52
P.S. This problem doesn't happen when I'm using Microsoft's Language Server instead.

**Comment by davidhalter** [comment] 2019-12-28 11:33
How are you using Jedi 0.15.2, it hasn't been upgraded yet: https://github.com/microsoft/vscode-python/issues/9243?

I cannot reproduce this. Can you give me a reproduction case that includes the parent directory as a ZIP file? It would be even more interesting if we have the same code so run `python3.8 -c "import jedi; print(jedi.Script(path='test.py', line=2, column=14).completions())"`. 

For me this returns `[<Completion: f1>]`. I removed the comment from test.py. Note that in Jedi line numbers are one based and columns zero based.

**Comment by davidhalter** [comment] 2019-12-28 11:34
And BTW, if I just execute the Python file, I get this:

```
$ python3.8 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from . import hello
ImportError: attempted relative import with no known parent package
```

**Comment by erezsh** [comment] 2019-12-28 13:07
Thanks for the prompt reply.

> How are you using Jedi 0.15.2, it hasn't been upgraded yet

I upgraded using pip. Perhaps that's not the correct way to do it. If so, how can I find the version that vscode uses?

Using the command you provided, I get the same result:
```bash
> python -c "import jedi; print(jedi.Script(path='test.py', line=2, column=14).completions())"
[<Completion: f1>]
```

So it seems that Jedi is capable of it (and I was very surprised to think that it didn't).

But still it doesn't work in vscode! (and yes, I'm sure jedi is enabled)

What should be my next step?

P.S. I'm running on Windows, but I can't imagine that this is the reason.

**Comment by davidhalter** [comment] 2019-12-28 16:12
No zip is not necessary if it works for you locally. I have unfortunately no idea why it's not working inside VScode. 

So please check if the above is also working in 0.15.1 (this is the version VScode is currently using).

If this is also working, please post an issue in the VSCode tracker. I will close this one then. It looks like everything in OK in Jedi.

**Closed** 2019-12-28 16:12 UTC
Labels: discussion

**Comment by erezsh** [comment] 2019-12-28 16:43
Yes, it's working in 0.15.1 too
