### ISSUE TITLE
Error getting completion params for `hashlib.blake2b`

### ISSUE THREAD

**Issue by hansonw** [davidhalter/jedi#1031] opened 2018-01-23 02:13 UTC
I'm able to consistently reproduce a `RuntimeError` running this code with Python 3.6.2 on MacOS:

```
>>> import jedi
>>> script = jedi.api.Script(source='from hashlib import ', line=1, column=20)
>>> c = script.completions()
>>> c[2]
<Completion: blake2b>
>>> c[2].params
Traceback (most recent call last):
  File "jedi/cache.py", line 116, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1978, in wrap_value
    value = eval(s, module_dict)
  File "<string>", line 1, in <module>
NameError: name '_blake2b' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1981, in wrap_value
    value = eval(s, sys_module_dict)
  File "<string>", line 1, in <module>
NameError: name '_blake2b' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi/cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "jedi/api/classes.py", line 350, in params
    return [Definition(self._evaluator, n) for n in get_param_names(context)]
  File "jedi/api/classes.py", line 342, in get_param_names
    return list(context.get_param_names())
  File "jedi/evaluate/compiled/__init__.py", line 139, in get_param_names
    signature = inspect.signature(obj)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 3033, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2783, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2324, in _signature_from_callable
    return _signature_fromstr(sigcls, obj, text_sig)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2049, in _signature_fromstr
    p(name, default)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2019, in p
    default_node = RewriteSymbolics().visit(default_node)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2006, in visit_Attribute
    return wrap_value(value)
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1983, in wrap_value
    raise RuntimeError()
```

There aren't any references to `_blake2b` in the actual `hashlib.py` library code, so the error seems pretty unusual. Is this a known issue? Thanks!

**Comment by davidhalter** [comment] 2018-01-26 00:05
Thanks for the detailed report.

This is definitely not a known issue. It looks like `inspect.signature(obj)` raises a RuntimeError. This feels very unusual and as probably not happened before.

I can even reproduce this one on linux. Let me investigate a bit. My first impression is that `inspect.signature` raises all sorts of errors that we basically just want to ignore...

**Comment by davidhalter** [comment] 2018-01-26 00:32
Fixed in the virtualenv branch. Might take a month or even a bit more until that one is released.

**Closed by davidhalter** 2018-01-26 00:32 UTC
