### ISSUE TITLE
Window gvim completion will pop gvim window

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1072] opened 2018-04-03 11:40 UTC
OS: Window7
jedi-vim and lastest commit jedi when completion will pop vim window.

code `jedi/api/environment.py` line 76
```
 class DefaultEnvironment(Environment):
     def __init__(self):
        super(DefaultEnvironment, self).__init__(sys.prefix, sys.executable)
```
sys.executable is `gvim.exe` 
After I modified it with `python3.exe`, It will pop console window.

code `jedi/evaluate/compiled/subprocess/__init__.py ` line 141:
```
        return subprocess.Popen(
            args,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
        )
```
can be use `shell=True` hide it.

**Comment by davidhalter** [comment] 2018-04-04 20:25
I have no idea what you're trying to report here. Why is the console window popped and what is it even? And BTW next time use the jedi-vim tracker, this is the wrong one ;-)

**Comment by bstaint** [comment] 2018-04-05 02:20
OK, I know, but I think question in `DefaultEnvironment` and `Popen` with jedi library.

Screeshot:
![gif](https://user-images.githubusercontent.com/5853792/38344101-36b24c22-3877-11e8-815c-9a9b7ad111d1.gif)

After I replaced sys.executable with `python.exe`
![gif2](https://user-images.githubusercontent.com/5853792/38344103-377545ba-3877-11e8-8a1b-c017a89fb232.gif)

And Popen parameter `cwd` should be used, Because when edited in UNC Path will raise `The subprocess python has crashed.`

**Comment by davidhalter** [comment] 2018-04-10 16:56
@micbou Do you have an idea what the issue is here? This might be a jedi issue. Not sure why the console window pops.

**Comment by micbou** [comment] 2018-04-10 17:19
The first issue is due to Jedi running inside Vim. For some reason, `sys.executable` is the Vim executable itself on Windows, which causes Jedi to start a new Vim when starting the process. This is rather hacky but a workaround could be to override the `sys.executable` value with `os.path.join( sys.prefix, 'python.exe' )` on Windows in jedi-vim.

The second issue can be fixed by passing a special flag `CREATE_NO_WINDOW` that tells Windows to not open a console when starting the process. Using `shell=True` is not recommended. See [the warning in the docs](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments).

**Comment by davidhalter** [comment] 2018-04-10 19:31
Wow. Ok.

How do we use the CREATE_NO_WINDOW flag? Like this: https://stackoverflow.com/a/44732558/552671?

The `sys.executable` seems to be wrong of course, however we might be able to correct that in jedi-vim. 

(Additionally, sys.prefix and sys.exec_prefix can be wrong if run inside a venv as well on Linux).

**Comment by micbou** [comment] 2018-04-10 19:38
> How do we use the CREATE_NO_WINDOW flag? Like this: https://stackoverflow.com/a/44732558/552671?

Yes, by setting `creationflags` to `0x08000000`. We may want to create a wrapper of `subprocess.Popen` that takes care of this.

**Comment by davidhalter** [comment] 2018-04-11 06:31
Makes sense!

**Comment by davidhalter** [comment] 2018-04-14 13:49
Can you please try again? You have to upgrade to latest jedi master. The window should not pop anymore.

Thank you for testing!

**Comment by bstaint** [comment] 2018-04-15 00:42
Yes, It's no problem.

**Comment by davidhalter** [comment] 2018-04-15 11:04
But you still replaced sys.executable, right?

**Comment by bstaint** [comment] 2018-04-15 14:41
It happen on before commit.

**Comment by davidhalter** [comment] 2018-04-15 14:47
Thanks for the report then :)

**Closed** 2018-04-15 14:47 UTC
