### ISSUE TITLE
jedi automatic completion missing

### ISSUE THREAD

**Issue by hqh2010** [davidhalter/jedi#2007] opened 2024-07-01 02:29 UTC
Hi, I encountered a problem while using the Jedi automatic completion function.
I have a wheel package. 'set_io' is a method in package. The source code is packaged with so using Cython tools and installed in a Python environment.
In this case, jedi is unable to automatically complete the parameter information of the function. May I ask if Jedi supports this usage scenario?(it works well in pycharm)
code:
![q1](https://github.com/davidhalter/jedi/assets/36130385/6599502f-6bde-4075-8bd5-197e6b3fb119)

The code run results are as follows:
![q2](https://github.com/davidhalter/jedi/assets/36130385/7fb5de59-eb31-47c5-b091-8662a7ffe917)

![q3](https://github.com/davidhalter/jedi/assets/36130385/7821762f-181d-4f63-8a33-e2c6bc9380cb)

**Comment by hqh2010** [comment] 2024-07-01 03:46
The ".pyi" file is stored in the same level directory as the so file.

**Comment by davidhalter** [comment] 2024-07-01 12:43
Can you show me the `pyi` file?

**Comment by davidhalter** [comment] 2024-07-01 12:44
And next time please don't post screenshots of texts. It is way better to have this in a way so I can copy it.

**Comment by hqh2010** [comment] 2024-07-01 13:32
> Can you show me the `pyi` file?
Tks you for your reply.

```
class Device:
    def __init__(self) -> None: ...
    def set_io(self, input: str, parameters: dict, current_output: str, dataset_out: str, output: str, log_out: str) -> None: ...
```
My wheel package is on the bastion machine，so I can't upload the wheel package to github directly. I confirm that the 'pyi file' can be recognized by pycharm.
the structure of wheel package are as follows:
esimkit
     |--edevice.cpython-39-x86_64-linux-gnu.so
     |--edevice.pyi
     | ...

**Comment by davidhalter** [comment] 2024-07-01 16:11
If I have no way to reproduce your problem you have to either help me or we can close the issue as well. It's pretty much impossible for me to debug this now.

**Comment by hqh2010** [comment] 2024-07-02 03:35
> If I have no way to reproduce your problem you have to either help me or we can close the issue as well. It's pretty much impossible for me to debug this now.

the wheel package and the source code 'test.py' are in the package, you can debug it. Tks a lot

[esimkit.zip](https://github.com/user-attachments/files/16061312/esimkit.zip)

**Comment by davidhalter** [comment] 2024-07-02 13:07
Can you provide me with a minimally reproducible example? It doesn't feel like I'm ever going to look into this otherwise.

**Comment by hqh2010** [comment] 2024-07-02 13:34
> Can you provide me with a minimally reproducible example? It doesn't feel like I'm ever going to look into this otherwise.

Actually, you only need to do two steps: 
Install the wheel package in 'build/dist', and then debug 'test.py'.

There may be version compatibility issues when installing the wheel package, so in case of incompatibility, you need to compile the wheel package yourself and install it. All operation steps are in README.md

**Comment by davidhalter** [comment] 2024-07-02 20:30
I don't think you understand, because you might be new to this:

It is not my job to do your work. You have to convince me that this is really a bug. And to do that you typically have to invest an hour or so to write up a good issue that is as small as possible. This is what I do and this is what all experienced devs to when they report issues. What you do is to throw a bunch of code at me and say "it doesn't work". That is not very helpful.

I'm going to close this issue for now until you provide me with a better reproduction. I'm happy to reopen if there's a minimal reproducible example.

**Closed by davidhalter** 2024-07-02 20:30 UTC
