### ISSUE TITLE
Jedi doesn't show available methods for instances

### ISSUE THREAD

**Issue by tarjeiba** [davidhalter/jedi#558] opened 2015-03-23 09:34 UTC
(This is a repost from the emacs-jedi issues, [Issue #212](https://github.com/tkf/emacs-jedi/issues/212).)

My configuration of jedi won't show available methods for an instance of a class, only for the class itself. The following will give no completion at the point

    import matplotlib.pyplot as plt
    
    fig = plt.figure()
    fig.

while a corresponding plt.Figure instead of fig. will show all available methods. Does anyone have an idea of what may be wrong?

**Comment by davidhalter** [comment] 2015-03-23 11:52
Hmm, what's your Jedi version? Have you tried the latest master branch?

**Comment by tarjeiba** [comment] 2015-03-23 14:01
Yes, I have tried using the latest master branch in a fresh python virtual environment with only matplotlib installed.

**Comment by tarjeiba** [comment] 2015-03-23 14:38
Could this be related to [Issue 372](https://github.com/davidhalter/jedi/issues/372)? I get autocomplete for `a.` in the snippet below, but not for `b.`

    import numpy as np
    a = [1,2]
    a.
    b = np.array([1,2])
    b.

**Comment by davidhalter** [comment] 2015-03-23 15:37
Can you give me the completion output of just `plt.figure`?

**Comment by tarjeiba** [comment] 2015-03-24 08:11
... I'm feeling less-than-bright here. Using the following snippet, I now get that `'Script' has no attribute 'complete'`:

    import jedi
    source = '''import matplotlib.pyplot as plt; plt.Figure.'''
    script = jedi.Script(source, 1, len(source), '')
    script.complete()

This is run in a fresh virtualenv with jedi version 0.9.0 and only matplotlib installed.

**Comment by tarjeiba** [comment] 2015-03-24 08:22
>>> import jedi
    >>> source1 = '''
    ... import matplotlib.pyplot as plt
    ... fig = plt.figure()
    ... fig.'''
    >>> source2 = '''
    ... import matplotlib.pyplot as plt
    ... plt.Figure.'''
    >>> script1 = jedi.Script(source1, 3, len('fig.'), 'example1.py')
    >>> script2 = jedi.Script(source2, 3, len('plt.Figure.'), 'example2.py')
    >>> completions1 = script1.completions()
    >>> print completions1[0].complete
    abs
    >>> completions2 = script2.completions()
    >>> print completions2[0].complete
    add_axes

...so everything seems to be in order. Still, no completion shows when used in Emacs.

**Comment by davidhalter** [comment] 2015-03-24 10:08
What you missed is that `func_closure` is the completion of a function object, not an actual class. People tend to think that numpy/matplotlib uses classes, that you instantiate. This is not true. Most of the time you call a function that returns you an object of something, but you don't call the object itself (because they need to handle the content of the object first). 

So what's happening here is simple, `plt.figure` is a function and therefore gets executed. The execution is too complicated for Jedi (i.e. matplotlib uses a weird caching mechanism that Jedi doesn't understand and therefore cannot evaluate the return value). 

This is not a bug - it's simply one of the things Jedi - at the moment - cannot understand, so I'm closing it.

**Closed by davidhalter** 2015-03-24 10:08 UTC

**Comment by tarjeiba** [comment] 2015-03-24 10:10
That explains it. Thanks for the thorough follow-up.

**Comment by davidhalter** [comment] 2015-03-24 10:40
If they are not working - yes! (I know that it's a function, so...)
