### ISSUE TITLE
PyGObject strange behavior

### ISSUE THREAD

**Issue by metal3d** [davidhalter/jedi#1365] opened 2019-07-05 21:45 UTC
I'm using jedi 0.14 with up to date deoplete and I've got a "almost" working interface.
What is very special is that:
[![asciicast](https://asciinema.org/a/ZB0l0N2qntM9V8NxV0APqkUdJ.svg)](https://asciinema.org/a/ZB0l0N2qntM9V8NxV0APqkUdJ)

If you take a look, some classes have no autocompletion. For exemple:
- `Gtk.Window` is ok
- `Gtk.ApplicationWindow` has no completion

Same for WebKit2.WebView that has no completion...

I know that introspecting `gi` is not easy. Thanks for you work.

PS: for a large variety of Gtk object, it's ok, and jedi + deoplete + nvim is the only one IDE I have that can complete correctly, so one more time: congrats

**Comment by metal3d** [comment] 2019-07-05 21:53
One note, the ascinema capture is "broken", I've got colors in the real term.

Changing `TERM`:
[![asciicast](https://asciinema.org/a/4MbTDWCTJfuSkShPhfsYWlIM9.svg)](https://asciinema.org/a/4MbTDWCTJfuSkShPhfsYWlIM9)

**Comment by davidhalter** [comment] 2019-07-10 08:02
I'm closing this, because I won't look into PyGObjects. If you want good completions, please use/provide stub files. There everything works. Binary objects like PyGObject are a pain and they will only work sometimes.

So please either find the actual issue and we discuss this (I doubt there is one, it's probably just impossible for Jedi to figure out what the issue is here) or use stubs.

**Closed by davidhalter** 2019-07-10 08:02 UTC
