### ISSUE TITLE
Rename no longer working

### ISSUE THREAD

**Issue by igordertigor** [davidhalter/jedi#1831] opened 2022-01-10 11:25 UTC
Since about a week or two, jedi rename stopped working. When I press `<leader>-r`, I see a message in the status line, which says: `:call jedi#rename()`, but nothing else happens. I would expect the following behaviour:

1. The variable name under the cursor gets removed and vim enters insert-mode
2. I type a new name and hit esc.
3. vim/jedi replaces all other uses of that variable (within the current scope) by the new name.
4. The status messages shows the number of replacements.

Has there been an update that I missed that could have broken this? I'm not aware of any configuration changes on my side (in fact I was on vacation and didn't even use my computer), with one exception: I changed my terminal emulator to alacritty. However, the same behaviour still remains with other terminal emulators (xterm and gnome-terminal).

I'm using neovim 0.4.3 on ubuntu 20.04.

**Comment by davidhalter** [comment] 2022-01-10 19:13
Hi Igor

Would it be possible to head over to https://github.com/davidhalter/jedi-vim/ and post your issue there? If the cause of the issue was clear, I would just move it. But this feels like a specific issue with your setup where we would need the debug output (you will see what you have to do to get that when you open an issue in jedi-vim).

I'm closing this here, because as far as I am concerned renames are still working (I just tried locally and the CI is green).

**Closed by davidhalter** 2022-01-10 19:13 UTC

**Comment by igordertigor** [comment] 2022-01-12 14:26
I found the issue: The `g:python3_host_prog` was set to a python in a virtual environment, but that virtual environment was broken.
