### ISSUE TITLE
Jedi crashes virtualenv python process

### ISSUE THREAD

**Issue by brupelo** [davidhalter/jedi#1191] opened 2018-08-01 16:07 UTC
REQUIREMENTS
-------

 - jedi==0.12.1
 - Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32 as a system-wide and as a virtualenv
 - windows7

STEPS TO PRODUCE CONSISTENT CRASHES
-------

Consider the below snippet:

    import json
    from collections import defaultdict

    import jedi

    if __name__ == "__main__":
        # env = jedi.create_environment("d:/virtual_envs/py364_32/Scripts/python.exe")
        env = jedi.create_environment("d:/software/python364_32/python.exe")

        script = jedi.Script(
            source="""import """,
            line=1,
            column=7,
            path='',
            encoding='utf-8',
            environment=env,
            sys_path=None,
        )

        errors = defaultdict(int)
        tracebacks = set()

        for c in script.completions():
            try:
                print(c.name, c.type, c.params)
            except Exception as e:
                import traceback
                tracebacks.add(traceback.format_exc())
                errors[str(e)] += 1

        print(json.dumps(errors, indent=4))
        for t in tracebacks:
            print(t)

If I run it using system-wide python such as `env = jedi.create_environment("d:/software/python364_32/python.exe")` I'll get normal exceptions such as, so far so good:

    {
        "There are no params defined on this.": 322
    }
    Traceback (most recent call last):
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 140, in wrapper
        return dct[key]
    KeyError: ((), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sources\personal\python\pyframework\jedi_crash.py", line 25, in <module>
        print(c.name, c.type, c.params)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 142, in wrapper
        result = method(self, *args, **kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\api\classes.py", line 345, in params
        raise AttributeError('There are no params defined on this.')
    AttributeError: There are no params defined on this.

At the moment I try to use a virtualenv such as `env = jedi.create_environment("d:/virtual_envs/py364_32/Scripts/python.exe")` jedi will make crash python process, here's the output produced by the above snippet:

    {
        "There are no params defined on this.": 3,
        "The subprocess d:\\virtual_envs\\py364_32\\Scripts\\python.exe has crashed (EOFError('Ran out of input',), stderr=b'').": 1,
        "The subprocess d:\\virtual_envs\\py364_32\\Scripts\\python.exe has crashed.": 755
    }
    Traceback (most recent call last):
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 140, in wrapper
        return dct[key]
    KeyError: ((), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 210, in _send
        is_exception, traceback, result = pickle_load(self._process.stdout)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\_compatibility.py", line 452, in pickle_load
        return pickle.load(file, encoding='bytes')
    EOFError: Ran out of input

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sources\personal\python\pyframework\jedi_crash.py", line 25, in <module>
        print(c.name, c.type, c.params)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 142, in wrapper
        result = method(self, *args, **kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\api\classes.py", line 343, in params
        followed = list(self._name.infer())
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 173, in infer
        level=self._level,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 280, in follow
        return self._do_import(self.import_path, self.sys_path_with_modifications())
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 368, in _do_import
        safe_module_name=True,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 503, in _load_module
        module = compiled.load_module(evaluator, path=path, sys_path=sys_path)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\__init__.py", line 36, in load_module
        access_path = evaluator.compiled_subprocess.load_module(**kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 94, in wrapper
        kwargs=kwargs,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 166, in run
        return self._send(id(evaluator), function, args, kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 221, in _send
        stderr,
    jedi.api.exceptions.InternalError: The subprocess d:\virtual_envs\py364_32\Scripts\python.exe has crashed (EOFError('Ran out of input',), stderr=b'').

    Traceback (most recent call last):
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 140, in wrapper
        return dct[key]
    KeyError: ((), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sources\personal\python\pyframework\jedi_crash.py", line 25, in <module>
        print(c.name, c.type, c.params)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 142, in wrapper
        result = method(self, *args, **kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\api\classes.py", line 345, in params
        raise AttributeError('There are no params defined on this.')
    AttributeError: There are no params defined on this.

    Traceback (most recent call last):
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 140, in wrapper
        return dct[key]
    KeyError: ((), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sources\personal\python\pyframework\jedi_crash.py", line 25, in <module>
        print(c.name, c.type, c.params)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\cache.py", line 142, in wrapper
        result = method(self, *args, **kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\api\classes.py", line 343, in params
        followed = list(self._name.infer())
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 173, in infer
        level=self._level,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 280, in follow
        return self._do_import(self.import_path, self.sys_path_with_modifications())
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\imports.py", line 358, in _do_import
        sys_path=sys_path,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 94, in wrapper
        kwargs=kwargs,
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 166, in run
        return self._send(id(evaluator), function, args, kwargs)
      File "d:\virtual_envs\py364_32\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 189, in _send
        raise InternalError("The subprocess %s has crashed." % self._executable)
    jedi.api.exceptions.InternalError: The subprocess d:\virtual_envs\py364_32\Scripts\python.exe has crashed.

**Comment by davidhalter** [comment] 2018-08-01 20:43
That's a hard one. I think we need to wait until #1169 is merged. At that point we can then have more information about this.

**Comment by brupelo** [comment] 2018-08-01 21:28
I assume from your answer you've already identified what those crashes are all about, ok, when you consider we need to test again please let me know and I'll check against the version you tell me to.

Btw, good news, at first I thought the crash would be related to the fact I'd tested the snippet with a really meaty virtualenv (~200pip packages) but now I've tested again with a fresh empty virtualenv and you can also reproduce the crash succesfully as well ;)

**Comment by davidhalter** [comment] 2018-08-01 21:48
It's probably a very simple issue, but as long as we don't have debug output we will not find the reason. 

I'll definitely get back to you once we have better debugging tools to figure out what your exact problem is. If you just want to try things, you might want to try switching Python versions on the virtualenv - maybe that helps, but I have no idea. You can also disable sys.stderr capturing (see pull request) to see what the issue is.

**Comment by mashu** [comment] 2018-11-19 20:32
Seems like I am hitting the same bug. I am trying to use use python-language-server in Emacs which in turn uses jedi.
When I had python-language-server systemwide than it kind of worked, but as soon as I switched to pyvenv I get this very exact error. 

So it really looks like something with jedi and virtual enviroment.

**Comment by gns26** [comment] 2018-12-11 15:58
Hi - is there any update on this? I think the relevant commit has gone in for #1169 so maybe further investigation can be done on this now?

Cheers

**Comment by davidhalter** [comment] 2019-02-24 23:47
The latest release should have fixed all of this. (See release notes).

The only thing that might not be fixed is @vblazhkun's issue. Please open a new ticket for this one.

**Closed by davidhalter** 2019-02-24 23:47 UTC
