### ISSUE TITLE
UnboundLocalError: local variable 'builtin_func' referenced before assignment

### ISSUE THREAD

**Issue by sergei-grechanik** [davidhalter/jedi#1255] opened 2018-11-23 11:28 UTC
Hello, I often get the UnboundLocalError when using youcompleteme in vim. I can't be sure that this problem is solely jedi's fault, but adding `builtin_func = None` into `SpecialMethodFilter.SpecialMethodName.infer` [here](https://github.com/davidhalter/jedi/blob/3bdb941daa2d87947fa265ebcf7d94f68efbc42d/jedi/evaluate/filters.py#L345) seems to solve the issue.

**Comment by davidhalter** [comment] 2018-12-23 14:42
Since the builtin handling has changed, could you please use the typeshed branch? It might be fixed there already, because I specifically worked on this class.

Also if you want to help me reproduce it, please try to print/log the name that was being searched as well as `self`. That would help a lot.

**Comment by davidhalter** [comment] 2018-12-25 11:44
Great! I'm closing, please let me know if it happens again, I will of course reopen. I'm also happy to receive other bug reports about the typeshed branch.

**Closed by davidhalter** 2018-12-25 11:44 UTC
