### ISSUE TITLE
Issue with @staticmethod Decorator

### ISSUE THREAD

**Issue by Cethyrion** [davidhalter/jedi#1420] opened 2019-10-07 03:49 UTC
Same as the issue for microsoft's python-language-server: https://github.com/microsoft/python-language-server/issues/208

methods with the @staticmethod decorator do not recognize type-wise that the first parameter is not self and therefore the same type as self

**Comment by davidhalter** [comment] 2019-10-07 21:03
Thanks for the issue. It's unfortunately a long standing issue. It's the oldest open bug. 

Duplicate of https://github.com/davidhalter/jedi/issues/735.

**Closed by davidhalter** 2019-10-07 21:03 UTC
