### ISSUE TITLE
function chain calls

### ISSUE THREAD

**Issue by 1014661165** [davidhalter/jedi#1852] opened 2022-04-20 03:08 UTC
Why does jedi analyze function chain calls only analyze the first three？
exp: s.a().b().c().d().e()
jedi only find definitions and references of a,b and c，but d and e only has definition, reference is lacked.

**Comment by davidhalter** [comment] 2022-04-20 06:49
There is no limitation about this. My guess is that some sort of inference limit comes into play, since this example works:

```
class X:
    def a(self):
        return self

X().a().a().a().a().a()
```

The limits generally exist to avoid extremely slow calculations and avoid Python recursion limits.

I'm closing until I have a way more thorough reproducer.

**Closed by davidhalter** 2022-04-20 06:49 UTC

**Comment by 1014661165** [comment] 2022-04-21 02:16
Dear davidhalter:
&nbsp; &nbsp; I'm glad to see that you replied for my issue.I'm sorry for my&nbsp;vague description about the bug.You may reproduce the bug like this:
1. define a class:
class Student:
&nbsp; &nbsp; def __init__(self):
&nbsp; &nbsp; &nbsp; &nbsp; self.id = 0
&nbsp; &nbsp; &nbsp; &nbsp; self.name = ''
&nbsp; &nbsp; &nbsp; &nbsp; self.age = 0
&nbsp; &nbsp; &nbsp; &nbsp; self.gender = ''
&nbsp; &nbsp; &nbsp; &nbsp; self.grade = 0


&nbsp; &nbsp; def set_id(self, id):
&nbsp; &nbsp; &nbsp; &nbsp; self.id = id
&nbsp; &nbsp; &nbsp; &nbsp; return self


&nbsp; &nbsp; def set_name(self, name):
&nbsp; &nbsp; &nbsp; &nbsp; self.name = name
&nbsp; &nbsp; &nbsp; &nbsp; return self


&nbsp; &nbsp; def set_age(self, age):
&nbsp; &nbsp; &nbsp; &nbsp; self.age = age
&nbsp; &nbsp; &nbsp; &nbsp; return self


&nbsp; &nbsp; def set_gender(self, gender):
&nbsp; &nbsp; &nbsp; &nbsp; self.gender = gender
&nbsp; &nbsp; &nbsp; &nbsp; return self


&nbsp; &nbsp; def set_grade(self, grade):
&nbsp; &nbsp; &nbsp; &nbsp; self.grade = grade
&nbsp; &nbsp; &nbsp; &nbsp; return self


2. use function chain calls:
&nbsp; &nbsp; s = Student()
&nbsp; &nbsp; s.set_id(1).set_name('1').set_age(1).set_gender('male').set_grade(1)


3. use jedi analyse the references of the above code:
&nbsp; &nbsp; for reference in references:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for target in reference.goto(follow_imports=True, follow_builtins_imports=True):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.......


When i debug the program, i found that the first time the program ran to the above for loop,&nbsp;
the 'goto' function could return the definitions of set_id, set_name, set_age, set_gender and set_grade.
But in the second time, it only return the definitions of set_id, set_name, set_age, set_gender and&nbsp;
set_grade got empty list, and i changed the order of the function calls, but it still return the first 3.
So i'm thinking that whether there is a limit in the jedi settings,but i couldn't find it.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davidhalter/jedi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davidhalter/jedi] function chain calls (Issue #1852)





 
There is no limitation about this. My guess is that some sort of inference limit comes into play, since this example works:
 class X:     def a(self):         return self X().a().a().a().a().a()  
The limits generally exist to avoid extremely slow calculations and avoid Python recursion limits.
 
I'm closing until I have a way more thorough reproducer.
