### ISSUE TITLE
Error when completing

### ISSUE THREAD

**Issue by nmiculinic** [davidhalter/jedi#730] opened 2016-06-07 19:41 UTC
Jedi throws error when completing following code

```
import tensorflow as tf
tf.<activate autocomplete>
```

I'm using python 3.5 and tensorflow 0.9.0rc0. Jedi version is 0.9.0. 
Error which I get is following:

```
Traceback (most recent call last):
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/_compatibility.py", line 24, in find_module_py33
    loader = importlib.find_loader(string)
  File "/usr/lib/python3.5/importlib/__init__.py", line 87, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: google.__loader__ is None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 340, in watch
    self._process_request(self._input.readline())
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 331, in _process_request
    request.get('prefix', '')))
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 142, in _serialize_completions
    description = completion.docstring()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 449, in docstring
    followed = self._follow_statements_imports()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 281, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 327, in _do_import
    find_module(import_parts[-1])
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/_compatibility.py", line 28, in find_module_py33
    raise ImportError("Originally ValueError: " + e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

**Comment by davidhalter** [comment] 2016-07-03 14:32
Can you retry with the latest master?

**Comment by sadovnychyi** [comment] 2016-07-13 10:26
I can confirm that it works completely with python 2, but in 3.5 I'm getting exception while trying to get completion type or docstrings:

```python
import jedi
s = jedi.Script('''import tensorflow
tensorflow.''', 2, len('tensorflow.'))
s.completions()
for c in s.completions():
  print(c.name)
  print(c.type)
  print(c.docstring())
```

Cropped output with many successful completions before:

```
bytes
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/api/classes.py", line 466, in type
    followed = self.follow_definition()
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/api/classes.py", line 494, in follow_definition
    defs = self._follow_statements_imports()
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/api/classes.py", line 481, in _follow_statements_imports
    return i.follow()
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/imports.py", line 253, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/imports.py", line 282, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/imports.py", line 282, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/evaluate/imports.py", line 328, in _do_import
    find_module(import_parts[-1])
  File "/Users/sadovnychyi/autocomplete-python/lib/jedi/_compatibility.py", line 42, in find_module_py33
    module_file = open(module_path, 'rb')
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py'
```

I will try to provide smaller test case if possible. Need some time to dig into it.

**Comment by sadovnychyi** [comment] 2016-07-13 10:36
It looks like it's an issue with "six" package for some reason.

```
import jedi
s = jedi.Script('''import six
six.''', 2, len('six.'))
s.completions()
for c in s.completions():
  print(c.name, c.full_name)
```

->

```
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py'
```

Works in python 2, does not work in python 3.5.

**Comment by davidhalter** [comment] 2016-07-17 09:15
I cannot reproduce it. Can you tell me what module_path at this point is? (With pdb or something similar).

**Comment by davidhalter** [comment] 2016-07-17 09:29
What OS are you on?

Also what error do you get if you run `python -c "open('DIR_DOESNT_EXIST/foo.py', 'rb')"`?

**Comment by sadovnychyi** [comment] 2016-07-17 11:17
I'm on macOS Sierra. Steps to reproduce:

* Completely uninstall tensorflow & six and make sure that no six presented in site-packages dir
* Install six using `easy_install six`
  As a result, I got only `six-1.10.0-py3.5.egg` file in my site-packages directory

```bash
/usr/local…on3.5/site-packages·ls | grep six
-rw-r--r--    1 sadovnychyi  staff    9030 Jul 17 19:03 six-1.10.0-py3.5.egg
```

```python
>>> import pdb
>>> import jedi
>>> s = jedi.Script('''import six
... six.''', 2, len('six.'))
>>> s.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/local/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 327, in _do_import
    find_module(import_parts[-1])
  File "/usr/local/lib/python3.5/site-packages/jedi/_compatibility.py", line 40, in find_module_py33
    module_file = open(module_path, 'rb')
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py'
>>> pdb.pm()
> /usr/local/lib/python3.5/site-packages/jedi/_compatibility.py(40)find_module_py33()
-> module_file = open(module_path, 'rb')
(Pdb) module_path
'/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py'
(Pdb) 
```

```bash
/usr/local…on3.5/site-packages·python -c "open('/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py', 'rb')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py'
```
Since it's not a directory, it's a zip-like egg file.

I'm not sure how popular .egg files are and if it's worth to support them though, but by default tensorflow uses it to install dependencies.

**Comment by davidhalter** [comment] 2016-07-17 11:27
`ls -la /usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg` ?

**Comment by sadovnychyi** [comment] 2016-07-17 15:06
```bash
~·ls -la /usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg                                
-rw-r--r--  1 sadovnychyi  staff  9030 Jul 17 19:03 /usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg
```

**Comment by davidhalter** [comment] 2016-07-17 15:44
What I don't get is: Why would opening this file raise a `NotADirectoryError` exception? This makes absolutely no sense to me, because it's obviously a normal file that we're trying to open as a normal file. Or is Python or OS X doing some fucked up magic on `open` calls? Can anybody explain this?

**Comment by sadovnychyi** [comment] 2016-07-17 15:47
No magic here.

`/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg` – this is file.
`/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py` – this is file inside of that .egg thing.

**Comment by davidhalter** [comment] 2016-07-17 16:03
Hmm to me this sounds like magic, because IMO it should raise the error `file does not exist` and not a directory error. I already struggle with the fact that the file system can open zip archives.

**Comment by sadovnychyi** [comment] 2016-07-17 16:09
```
/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py
                                                                 ^^^^^^^^^^^^^^^^^^^^^
                                                                this is not a dir, but existing file
```
And since we are trying to access a file "inside of that file" – we got not a directory exception. Seems legit. Does Jedi have any kind of support for zipped packages?

```
~·python -c "open('/usr/local/lib/python3.5/site-packages/pep8.py/bla', 'rb')"             
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/site-packages/pep8.py/bla'
```

Same thing here.

**Comment by davidhalter** [comment] 2016-07-17 17:48
> Does Jedi have any kind of support for zipped packages?

I don't think so. It would actually be nice to add that. :)

**Comment by sadovnychyi** [comment] 2016-07-18 13:31
FYI I got it working somehow. It's actually easy for py3 since you already
use module loaders there and for py2 its a bit more code. It's definitely
works for non-packages, still need proper testing for packages since I
don't know how do you read internal imports there. I'll make a pr soon!

**Comment by davidhalter** [comment] 2016-07-18 21:32
Thanks mate!! Really appreciate it. I think you're certainly on the right path (I just quickly looked at your PR). I will probably review it in two days.

Does Python 2 even do zip imports? I would say it does and we would probably have to copy some of the behavior of importlib. But I would even be fine if you full on copy certain parts. You don't need to rewrite it all.

**Comment by sadovnychyi** [comment] 2016-07-19 18:04
@davidhalter updated PR.

**Comment by davidhalter** [comment] 2016-07-30 12:20
@sadovnychyi Since the egg support is merged now, do you think we should close this issue?

**Comment by sadovnychyi** [comment] 2016-07-30 12:35
Sure. It's definitely works now. It actually did work even before if you haven't use `easy_install` to install some dependencies, [unlike](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation) how they advice you to do.

**Comment by shashank879** [comment] 2016-09-24 03:35
Hey, its still not working for me for some cases, like numpy.sign() does not appear. Its shows np.sin(), np.sinc() and np.size(), but not the sign() function.

**Comment by shashank879** [comment] 2016-09-24 03:36
Hey, its still not working for me for some cases, like numpy.sign() does not appear. Its shows np.sin(), np.sinc() and np.size(), but not the sign() function.

**Comment by sadovnychyi** [comment] 2016-09-24 09:51
@davidhalter here's small test case for @shashank879's issue to reproduce it:

```python
import jedi
s = jedi.Script('''import collections
Dataset = collections.namedtuple('Dataset', ['data'])
Datasets = collections.namedtuple('Datasets', ['train'])
train_x = Datasets(train=Dataset('data_value'))
train_x.train.''', 5, len('train_x.train.'))
assert 'data' in [c.name for c in s.completions()]
```

This could be moved to another issue.

**Closed** 2017-09-12 09:06 UTC
Labels: bug

**Comment by davidhalter** [comment] 2017-09-12 09:07
I think I fixed namedtuples for good, now. It was quite complicated, but now content access is finally possible - alongside a few other fixes
