### ISSUE TITLE
Completions are not provided for stub file unless it's located in the same folder as the .py file

### ISSUE THREAD

**Issue by AmjadHD** [davidhalter/jedi#1424] opened 2019-10-15 09:04 UTC
originally opened in https://github.com/palantir/python-language-server/issues/668
I have two files in one folder
mod.py
```python
def f(x):
    pass
```
and mod.pyi
```python
def f(x: int) -> int: ...
```
completions work fine
![image](https://user-images.githubusercontent.com/33235928/66136186-55c47080-e5fb-11e9-8baa-2dc8d4b5fc76.png)

then
1. create a stubs folder and move mod.pyi to it
2. add a mypy.ini
```ini
[mypy]
mypy_path = stubs
```
![image](https://user-images.githubusercontent.com/33235928/66135941-fa927e00-e5fa-11e9-8c54-faf79f67381d.png)
no completions are provided

Note that pyls uses the `completions()` method of `Script`:
https://github.com/palantir/python-language-server/blob/8db7654f9c3786f579416ec42e6a6625003ee43a/pyls/plugins/jedi_completion.py#L44

**Comment by davidhalter** [comment] 2019-10-17 23:22
mypy path changes are not supported. I feel like this is a duplicate of #1334. I'm therefore closing this one. Please give a :+1: in that thread if you guys want that to be done.

**Closed by davidhalter** 2019-10-17 23:22 UTC
