### ISSUE TITLE
[parser] AttributeError: "... Don't touch this (py__mro__)!" with Django's model Manager

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#533] opened 2015-01-19 16:32 UTC
When trying to complete the following via YouCompleteMe and jedi from the "parser" branch, I am seeing an error:

    from django.db.models import Manager

    m = Manager()
    m.

    AttributeError: Instance <eInstance of <CompiledObject: <type 'object'>>(<Arguments: Node(arglist, [<Name: metaclass@779,24>, <Operator: u','>, <String: 'temporary_class'>, <Operator: u','>, Node(atom, [<Operator: u'('>, <Operator: u')'>]), <Operator: u','>, Node(atom, [<Operator: u'{'>, <Operator: u'}'>])])>)>: Don't touch this (py__mro__)!

TEST CASE:

    jedi.Script("from django.db.models import Manager\nm = Manager()\nm.", 3, 2).completions()

This is with Django 1.7 (git).

It works with jedi-master, although it's missing most of the completions then.

This is how the manager is defined ([source](https://github.com/django/django/blob/master/django/db/models/manager.py#L240)):

    class Manager(BaseManager.from_queryset(QuerySet)):
        pass

The stacktrace:

      File "…/vim/neobundles/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 65, in ComputeCandidatesInner
        for completion in script.completions() ]
      File "jedi/jedi/api/__init__.py", line 183, in completions
        completion_names = get_completions(user_stmt, b)
      File "jedi/jedi/api/__init__.py", line 169, in get_completions
        completion_names += self._simple_complete(path, dot, like)
      File "jedi/jedi/api/__init__.py", line 245, in _simple_complete
        scopes = list(self._prepare_goto(path, True))
      File "jedi/jedi/api/__init__.py", line 285, in _prepare_goto
        scopes = self._evaluator.eval_statement(eval_stmt)
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/recursion.py", line 24, in run
        result = func(evaluator, stmt, *args, **kwargs)
      File "jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 121, in eval_statement
        types = self.eval_element(stmt.get_rhs())
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 155, in eval_element
        return self._eval_atom(element)
      File "jedi/jedi/evaluate/__init__.py", line 207, in _eval_atom
        return self.find_types(scope, atom, stmt.start_pos, search_global=True)
      File "jedi/jedi/evaluate/__init__.py", line 106, in find_types
        return f.find(scopes, search_global)
      File "jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "jedi/jedi/evaluate/finder.py", line 86, in find
        types = self._names_to_types(names, search_global)
      File "jedi/jedi/evaluate/finder.py", line 230, in _names_to_types
        new_types = _name_to_types(self._evaluator, name, self.scope)
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/finder.py", line 275, in _name_to_types
        types += _remove_statements(evaluator, typ, name)
      File "jedi/jedi/evaluate/finder.py", line 320, in _remove_statements
        types += evaluator.eval_statement(stmt, seek_name=name)
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/recursion.py", line 24, in run
        result = func(evaluator, stmt, *args, **kwargs)
      File "jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 121, in eval_statement
        types = self.eval_element(stmt.get_rhs())
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 168, in eval_element
        types = self.eval_trailer(types, trailer)
      File "jedi/jedi/evaluate/__init__.py", line 236, in eval_trailer
        new_types += self.execute(typ, node, trailer)
      File "jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 276, in execute
        types = func(self, arguments)
      File "jedi/jedi/evaluate/representation.py", line 420, in py__call__
        return [Instance(evaluator, self, params)]
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/cache.py", line 58, in __call__
        return super(CachedMetaClass, self).__call__(*args, **kwargs)
      File "jedi/jedi/evaluate/representation.py", line 106, in __init__
        method = self.get_subscope_by_name('__init__')
      File "jedi/jedi/evaluate/representation.py", line 180, in get_subscope_by_name
        sub = self.base.get_subscope_by_name(name)
      File "jedi/jedi/evaluate/representation.py", line 443, in get_subscope_by_name
        for s in [self] + self.py__bases__(self._evaluator):
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/representation.py", line 415, in py__bases__
        return list(chain.from_iterable(args.eval_args()))
      File "jedi/jedi/evaluate/param.py", line 133, in eval_args
        return [self._evaluator.eval_element(el) for stars, el in self._split()]
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/__init__.py", line 168, in eval_element
        types = self.eval_trailer(types, trailer)
      File "jedi/jedi/evaluate/__init__.py", line 234, in eval_trailer
        new_types += self.find_types(typ, node)
      File "jedi/jedi/evaluate/__init__.py", line 106, in find_types
        return f.find(scopes, search_global)
      File "jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "jedi/jedi/evaluate/finder.py", line 85, in find
        names = self.filter_name(scopes)
      File "jedi/jedi/evaluate/finder.py", line 175, in filter_name
        for names_dict, position in names_dicts:
      File "jedi/jedi/evaluate/finder.py", line 108, in <genexpr>
        return ((n, None) for n in self.scope.names_dicts(search_global))
      File "jedi/jedi/evaluate/representation.py", line 433, in names_dicts
        for scope in self.py__mro__(self._evaluator):
      File "jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "jedi/jedi/evaluate/representation.py", line 406, in py__mro__
        for cls_new in cls.py__mro__(evaluator):
      File "jedi/jedi/evaluate/representation.py", line 236, in __getattr__
        % (self, name))
    AttributeError: Instance <eInstance of <CompiledObject: <type 'object'>>(<Arguments: Node(arglist, [<Name: metaclass@779,24>, <Operator: u','>, <String: 'temporary_class'>, <Operator: u','>, Node(atom, [<Operator: u'('>, <Operator: u')'>]), <Operator: u','>, Node(atom, [<Operator: u'{'>, <Operator: u'}'>])])>)>: Don't touch this (py__mro__)!

**Comment by davidhalter** [comment] 2015-03-25 10:28
Still happening? I cannot reproduce it, I think I've fixed such an exception along the line. Seems to work now.

Closing it therefore. Please check again, if it doesn't work let me know.

**Comment by blueyed** [comment] 2015-03-25 11:51
Seems to work, as in "does not crash" - but does not provide completions.

Can this issue be used to track this, or should I create a new one?

**Comment by davidhalter** [comment] 2015-03-25 12:49
Hmm strange. It seems to work for me that's why I closed it.

>>> django.get_version()
'1.5.1'
>>> jedi.Script("from django.db.models import Manager\nm = Manager()\nm.", 3, 2).completions()
[<Completion: aggregate>, <Completion: all>, <Completion: annotate>, <Completion: bulk_create>, <Completion: complex_filter>, <Completion: contribute_to_class>, <Completion: count>, <Completion: create>, <Completion: creation_counter>, <Completion: dates>, <Completion: db>, <Completion: db_manager>, <Completion: defer>, <Completion: distinct>, <Completion: exclude>, <Completion: exists>, <Completion: extra>, <Completion: filter>, <Completion: get>, <Completion: get_empty_query_set>, <Completion: get_or_create>, <Completion: get_query_set>, <Completion: in_bulk>, <Completion: iterator>, <Completion: latest>, <Completion: model>, <Completion: none>, <Completion: only>, <Completion: order_by>, <Completion: prefetch_related>, <Completion: raw>, <Completion: reverse>, <Completion: select_for_update>, <Completion: select_related>, <Completion: update>, <Completion: using>, <Completion: values>, <Completion: values_list>, <Completion: _copy_to_model>, <Completion: _db>, <Completion: _inherited>, <Completion: _insert>, <Completion: _set_creation_counter>, <Completion: _update>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __doc__>, <Completion: __format__>, <Completion: __getattribute__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __new__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __str__>, <Completion: __subclasshook__>]

**Comment by blueyed** [comment] 2015-03-25 14:04
Oh, it works in Django 1.5.1 and 1.6.11 for me, too - but not with Django 1.7.7 anymore.
Also not with 1.8rc1, so this has changed in 1.7 probably.

**Comment by blueyed** [comment] 2015-03-25 14:09
I don't know if that's helpful, but here are some differences.

You'll have to look deeper into it probably yourself.

Maybe it's `six.with_metaclass(RenameManagerMethods)` which is problematic here..

With Django 1.7:

    class RenameManagerMethods(RenameMethodsBase):
        renamed_methods = (
            ('get_query_set', 'get_queryset', PendingDeprecationWarning),
            ('get_prefetch_query_set', 'get_prefetch_queryset', PendingDeprecationWarning),
        )


    class Manager(six.with_metaclass(RenameManagerMethods)):
        # Tracks each time a Manager instance is created. Used to retain order.
        creation_counter = 0

        def __init__(self):
            super(Manager, self).__init__()

With Django 1.6:

    class RenameManagerMethods(RenameMethodsBase):
        renamed_methods = (
            ('get_query_set', 'get_queryset', RemovedInDjango18Warning),
            ('get_prefetch_query_set', 'get_prefetch_queryset', RemovedInDjango18Warning),
        )


    @python_2_unicode_compatible
    class BaseManager(six.with_metaclass(RenameManagerMethods)):
        # Tracks each time a Manager instance is created. Used to retain order.
        creation_counter = 0

        def __init__(self):
            super(BaseManager, self).__init__()

    ...

    class Manager(BaseManager.from_queryset(QuerySet)):
        pass

**Comment by davidhalter** [comment] 2015-03-25 14:26
So are you not seeing any completions? I don't expect Jedi to give you proper completions for the metalass. That's just something that is not (yet) supported. Some of those cases might be soon, but it's not the case, yet.

If you still get at least the __init__ completion from above, everything is working fine.

You an of course add another issue (feature) to ask for supporting such simple meta class usages. (IIRC six.with_metaclass is very simple and just uses `type(...)`, so we would need to understand that.)

**Comment by blueyed** [comment] 2015-03-25 14:56
> So are you not seeing any completions?

Yes, an empty list.

**Comment by davidhalter** [comment] 2015-03-31 00:14
I'm closing this issue, since the bug has been fixed.

Regarding the meta class, `six.with_metaclass` looks like this:

```
def with_metaclass(meta, *bases):
    """Create a base class with a metaclass."""
    # This requires a bit of explanation: the basic idea is to make a dummy
    # metaclass for one level of class instantiation that replaces itself with
    # the actual metaclass.
    class metaclass(meta):

        def __new__(cls, name, this_bases, d):
            return meta(name, bases, d)
    return type.__new__(metaclass, 'temporary_class', (), {})
```

If you want to, you can open a new issue about supporting meta classes (and type calls). Jedi states in the docs that meta classes are not supported and it's unlikely to change in the near future. Not that I don't want to support them, but it's just really hard to actually do it.

**Closed by davidhalter** 2015-03-31 00:14 UTC
Labels: bug
