### ISSUE TITLE
`__signature__` and `__wrapped__` are ignored

### ISSUE THREAD

**Issue by athre0z** [davidhalter/jedi#1058] opened 2018-03-11 08:25 UTC
Let me begin by thanking your for your hard work on this project! It spared me many hours if not days of looking up stuff.

Moving on, currently assignments to `__signature__` and `__wrapped__` are ignored. Those allow for overriding the signature of a function with the signature of another, since Python 3.3. This is very useful for decorators that want to preserve the function signature of the wrapped function in auto-completion. `__wrapped__` is also set by `functools.wraps`.

```python
import jedi

source = '''
import inspect

def func1(blah: int, meow: float):
    pass

def func2(*args, **kwargs):
    pass

print(inspect.signature(func2))
func2.__signature__ = inspect.signature(func1)
func2.__wrapped__ = func1
print(inspect.signature(func2))

func2(
'''

script = jedi.Script(source, 15, 6)

for param in script.call_signatures()[0].params:
    print(param.description)
```

Executing the source yields:
```
(*args, **kwargs)
(blah:int, meow:float)
```

Executing with Jedi yields:
```
param *args
param **kwargs
```

The full order of how signature info should be obtained is [defined in PEP 362](https://www.python.org/dev/peps/pep-0362/#implementation). I understand this might be non-trivial to implement, but it'd improve usability of decorated functions immensely.

**Comment by davidhalter** [comment] 2018-03-12 00:51
Related to https://github.com/davidhalter/jedi/issues/634. Will be fixed in the same iteration.

It's a pretty hard thing to fix. You probably need to be patient.

**Comment by martinRenou** [comment] 2019-03-27 10:48
Did you find another way to mock the jedi completer @athre0z? I also would like to overwrite the `__signature__` for programmatically adding parameters to a class constructor that takes `kwargs`, but since it does not work with jedi I hoped there would be another way to achieve this. Maybe you have ideas @davidhalter?

**Comment by athre0z** [comment] 2019-03-27 10:50
Nope, still clicking through call-chains to manually look up things. :(

**Comment by martinRenou** [comment] 2019-03-27 12:36
Ok... Thanks anyway :). There must be a way to do that with jedi though. We need to take a look at how jedi is looking for the function arguments.

**Comment by martinRenou** [comment] 2019-03-28 17:13
Ok, so I just found out that it works just fine using the `typeshed` branch! :)

**Closed** 2019-07-28 22:37 UTC
Labels: feature

**Comment by davidhalter** [comment] 2019-07-28 22:39
Fixed partially. `wraps` is now supported, `*args, **kwargs` a lot better understood.

Modifying `__signature__` and `__wrapped__` will not be supported in the future. However, I doubt that anyone really needs this now. If you do, please let me know.

**Comment by davidhalter** [comment] 2019-10-30 00:22
@martinRenou Does your object have a signature? Because if it does (and you're using I think at least Python 3.5), it should work.

I'm not exactly sure what my comment was about, but I feel like it was about static analysis. This is probably not your issue, since you're working with the shell.

I have no idea what your issue could be, but as a first indicator, please provide `inspect.signature(...)` of your object. If that works, Jedi should work without issues.

**Comment by martinRenou** [comment] 2019-10-30 07:51
Thanks for your answer! Playing with `inspect.signature(...)` I found my issue. I was assigning to `cls.__init__.__signature__`, but `inspect` and `jedi` looks for `cls.__signature__`. It seems to work now!

**Comment by fmagin** [comment] 2019-11-10 12:19
I have a case which I think is related to this because it involves changing `__signature__`. 

The specific line/usecase I wish to support https://github.com/angr/angr/blob/e4fa663727003d059c24b1ecd4a880e60a5ef494/angr/analyses/analysis.py#L87

Example Setup:
```python
import inspect
import angr
proj = angr.Project('/bin/true', load_options={'auto_load_libs': False})
```

Check that inspect works:
```python
In [3]: inspect.signature(proj.analyses.CFGFast)                                                          
Out[3]: <Signature (binary=None, objects=None, regions=None, pickle_intermediate_results=False, symbols=True, function_prologues=True, resolve_indirect_jumps=True, force_segment=False, force_complete_scan=True, indirect_jump_target_limit=100000, data_references=False, cross_references=False, normalize=False, start_at_entry=True, function_starts=None, extra_memory_regions=None, data_type_guessing_handlers=None, arch_options=None, indirect_jump_resolvers=None, base_state=None, exclude_sparse_regions=True, skip_specific_regions=True, heuristic_plt_resolving=None, detect_tail_calls=False, low_priority=False, cfb=None, model=None, use_patches=False, start=None, end=None, collect_data_references=None, extra_cross_references=None, **extra_arch_options)>
```
Expected behavior:
```python
proj.analyses.CFGFast(for<tab>
```
This suggest the keyword arguments`force_complete_scan=` and `force_segment=` (also `for` and `format`) if `IPython.get_ipython().Completer.use_jedi == False`

When using jedi it just suggests `format`

I have no idea if this is the correct way to debug jedi but I tried
```python
txt = 'proj.analyses.CFGFast(force'

s = jedi.Interpreter(txt, [globals(), locals()], column=len(txt)-1)
```

in the same context and then `s.completions()` is the empty list.

I tried stepping through the jedi code (tag `v0.15.1`, for some reason master doesn't work when running from PyCharm) and the issue might be somewhere else. https://github.com/davidhalter/jedi/blob/c3d40949b1d9222dae1a7132ca0fbeecb6e4069e/jedi/api/__init__.py#L351 doesn't return anything so the search for parameters might never happen. I do not understand the code enough to judge that though, maybe this happens somewhere else. If this is just doing syntactical analysis it can't really know what `CFGFast` is and what signature it has.


This factory pattern seems like it could be common enough to support. Maybe my way of implementing this in the angr codebase is incorrect, but it allows the IPython help and non jedi tab completion to work, so I'd expect it to work with jedi.

**Comment by davidhalter** [comment] 2019-12-01 00:40
>  for some reason master doesn't work 

You need parso master, too. Sorry for that.

Everything apart from that was right on track. I have no idea why this fails for you. But if you want to keep discussing this, please open a new issue. This is far enough away from the original one.
