### ISSUE TITLE
ValueError when completing os

### ISSUE THREAD

**Issue by spaceotter** [davidhalter/jedi#908] opened 2017-04-09 19:08 UTC
Executing this code on Windows 10 + Python 2.7 + jedi 10.2:
```python
import jedi
s = jedi.Script('''import os
os.''', 2, len('os.'))
s.completions()
for c in s.completions():
  print(c.name, c.full_name)
```
Gives this result:
```
('abort', 'nt.abort')
('access', 'nt.access')
('altsep', 'str')
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(c.name, c.full_name)
  File "c:\Python27\lib\site-packages\jedi\api\classes.py", line 301, in full_name
    path = list(self._path())
  File "c:\Python27\lib\site-packages\jedi\api\classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "c:\Python27\lib\site-packages\jedi\api\classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: need more than 0 values to unpack
```

**Comment by dsedivec** [comment] 2017-04-14 17:25
FYI this looks like the same problem as in #907.

**Comment by davidhalter** [comment] 2017-09-13 08:19
Duplicate of #907.

**Closed by davidhalter** 2017-09-13 08:19 UTC
