### ISSUE TITLE
x.real crashes deoplete

### ISSUE THREAD

**Issue by SolidTux** [davidhalter/jedi#1527] opened 2020-03-16 14:36 UTC
I'm using jedi 0.16.0 on Fedora 31 with Python 3.7.6 with deoplete in neovim.

```python
import numpy as np
import scipy.optimize as opt


def analytic(x, c, phi):
    x = x.astype(np.complex)
    res = c * np.power(np.tan(np.pi/4 + phi), -x/beta)
    res[x > 0] *= -1
    return res


popt, pcov = opt.curve_fit(
    lambda x, c, phi: np.real(analytic(x, c, phi)), x, y)
analytic(df['tau'], *popt)
```

The crash happens when I change `res[x > 0]` to `res[x.real > 0]` (or .anything for that matter) and exit insert mode (see screencast below). Strangely it is really sensitive to changes to anything. With `res = np.sin(x)` or `res = np.zeros_like(x)` etc. instead of the power-tan line it doesn't crash. Also removing any line changes the behaviour as well.

![screencast](https://user-images.githubusercontent.com/17935831/76767737-58c2b000-679a-11ea-9c1f-70b4a5185857.gif)

I tried to get a log from that with

```vim
call deoplete#custom#option('profile', v:true)
call deoplete#enable_logging('DEBUG', 'deoplete.log')
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)
```

But only deoplete stuff appeared in the [log](https://gitlab.com/snippets/1953803).

**Comment by davidhalter** [comment] 2020-03-21 16:33
I cannot reproduce. Please send me the full traceback. I'm not going to install debug deoplete.

**Comment by davidhalter** [comment] 2020-03-29 17:37
Closing, because there was no answer. I'm happy to reopen if a full traceback is provided.

**Closed by davidhalter** 2020-03-29 17:37 UTC
