### ISSUE TITLE
Speed issues when setting an Environment

### ISSUE THREAD

**Issue by relikd** [davidhalter/jedi#1682] opened 2020-10-18 09:21 UTC
Hi dear people,

I have spent a few hours into anaylzing why my Anaconda / Jedi is performing so slow. Characters in the (anaconda) popup appear real slow a few seconds after they are typed. Autocompletion behaves similar.
I already found the cause for this in Anaconda, https://github.com/DamnWidget/anaconda/issues/878#issuecomment-710664767.

It seems, setting `VIRTUAL_ENV` is causing the behavior in Jedi. As nothing else has changed in the Anaconda source I am now assuming that Jedi has a different logic if an environment is set.
Can some please confirm or refute my assumption?

Do you have a test suit that checks the performance between setting the env or not?

**Comment by davidhalter** [comment] 2020-10-19 20:45
Jedi version?

**Comment by relikd** [comment] 2020-10-19 21:01
v0.17.1

**Comment by davidhalter** [comment] 2020-10-19 22:46
Can you upgrade to 0.17.2 and retry?

**Comment by relikd** [comment] 2020-10-19 23:27
Just tried, did not change anything. 
The loading of the auto-completion list takes about 3 seconds. Parameter expansion about the same, 3 seconds. And it gets slower with time. I had situation where I tap tab to complete the parameters and the UI won't show anything. Until 30 seconds later it pasted the parameters somewhere completely unrelated in the middle of another text.

**Comment by davidhalter** [comment] 2020-10-21 23:08
I only skimmed the issue https://github.com/DamnWidget/anaconda/issues/878#issuecomment-710664767.

I'm not really sure what it could be, but it looks like the anaconda implementation is not using the Jedi API in its intended way.

It looks like your issue is probably an environment that is reloaded on each auto completion approach. That would make it just very slow. I guess you are using very simple completions?

**Comment by relikd** [comment] 2020-10-22 06:56
I have not tested very simple completions but would assume that it would be slow too. It feels like jedi recreates the cached index with every character I type. And as said in the other issue, I tested by setting `VIRTUAL_ENV` before each invocation. That should be the same as setting the var directly – which is how jedi reads environments.

**Comment by davidhalter** [comment] 2020-10-22 07:18
You still haven't answered my question.

**Comment by relikd** [comment] 2020-10-22 07:40
I have only tested with libraries, in particular with a self-written library (~400 lines). Because that is how I can compare whether one is faster than the other. This issue appears for said library and for system libraries. I have not tested for, e.g., function completion inside the same file, because Sublime has also a completion function that would interfere with the testing. Sublime auto-completes every word that is already present in the document.

**Comment by davidhalter** [comment] 2020-10-23 16:01
Closing, because the downstream issue was closed.

If there's really an issue, I would probably need more debugging, why this happens. It would of course be interesting to have a pure Python reproduction. If we have that I'm happy to investigate.

**Closed by davidhalter** 2020-10-23 16:01 UTC
